### PR TITLE
Update?

### PR DESCRIPTION
**Pull request by MirandaDufrane**
Perhaps update the modded version to the newest version? I can't go back to the original so I'd love to see more improvements on this one. Also perhaps make it is you get eggs that you haven't had before if you can and mutations are more likely to happen? Sorry if this is a lot, I just love this version so much more then the original. Thank you.

### CODE REVIEW

**Comment by PixLSteam** [comment]
This was supposed to be an issue instead of a PR, right? Anyway, any kind of automation or RNG reduction is unlikely to get approval from the devs. Feel free to give it a shot though.

**Comment by MirandaDufrane** [comment]
Oh I thought this was a suggestion space. I apologize. Sorry for wasting
your time

**Comment by PixLSteam** [comment]
You can leave suggestions using [this link](https://github.com/pokeclicker/pokeclicker/issues/new?assignees=&labels=&template=suggestion.md&title=%5BSUGGESTION%5D+). Pull requests are used for adding to the code.

**Comment by MirandaDufrane** [comment]
Should I copy and paste?

**Comment by PixLSteam** [comment]
Usually you'd create a suggestion/issue for each feature/change you want. A neat list of separate and detailed suggestions might be okay too, but it would make working with this a bit harder - separate issues are preferred. Like I said, most of these are very likely to get thrown out immediately, but if you have any QoL suggestions that don't just make the game easier for no reason feel free to submit them.

**Comment by MirandaDufrane** [comment]
Gotcha...

**Comment by anapple96** [comment]
People focused on the fact that an issue is presented as a PR while completely forgetting the fact that this issue is asking the PokeClicker dev to update the hacked version, which will get immediately shot down if an issue is opened anyway lol

**Comment by MirandaDufrane** [comment]
TBH, I thought it was a separate discord for the hacked version. Now I just
feel embarrassed...again, I'm sorry, I just misunderstood. I've been trying
to g t in contact with the person who made the hacked version so he could
update it, but I haven't been able to get a hold of them. I DO like the
original version, but it just takes way too long when in the hacked
version, it takes just 3 or 4 days to complete 3 different regions yet it's
still a real challenge to do. In my opinion, it's better that way, but
others might not feel the same way. I really should have thought this
through abit more and not send it when I was half way asleep. I'm really
really sorry if I offended you or the dev or if you ARE the dev. I just
wanted things to be slightly easier for myself and other players who are
struggling with progression in the game.

**Comment by Ultima1990** [comment]
It is in fact very possible to have a wrong opinion.

**Comment by MirandaDufrane** [comment]
Ok, if so, please explain to me how so I don't make the same mistake again.
I want to learn from this conversation we're having about a little screw up
on my end and wrong opinions. I wanna leave with more knowledge than I came
here with, so please let me know in as much detail as possible so I know
that opinions can indeed be wrong.

**Comment by GarrikFel** [comment]
Ultima1990 has the opinion that opinions can be wrong.  Are you saying that this is wrong?

I was going to say more, but that's the heart of the issue.  If you are trying to convince someone that they are wrong... about their opinion that opinions can be wrong... anything you say will only prove them right.

**Pull request closed without merging**
