### PR TITLE
Add defender type to hatchery settings for breeding efficiency calculation

### PR DESCRIPTION
**Pull request by Alderi-Tokori**
Implements suggestion #3850

### CODE REVIEW

**Comment by CooldudeOmega** [comment]
I think defender should be changed to defending but from the slightly more than usual I can gauge from the code this looks good

**Comment by Alderi-Tokori** [comment]
I just realized I put all my code in the "wrong" module; since it's intended to be in the hatchery settings, it shouldn't be in the BreedingFilters, but directly in the BreedingController (in the same fashion as the regionalAttackDebuff), I'll change this so it's coherent with the rest.

I'll also change "defender" to "defending".

**Comment by Alderi-Tokori** [comment]
It's fixed, now the defending type settings are handled in the BreedingController.

**Comment by Jaaslet** [comment]
Sorry for waiting this long to respond. It was not easy to figure out what to do with this PR.
We are going to close it. Very few players will want to use it, and it adds more stuff to an already confusing UI

**Pull request closed without merging**
