### PR TITLE
Initial SVG implementation for Unova

### PR DESCRIPTION
**Pull request by HLXII**
Notes:
I've pulled the map image from anapple's branch. Not sure if that's the final version though.

Not entirely sure what town exists where Black City/White Forest is. I've left it as "???" for now.
There doesn't seem to be a dock in Unova right now. Not sure if that just wasn't implemented yet, so I commented out the dock for now.
Castelia city has a dungeon, and what seems to be some type of machine/gate thing near it. I'm not sure what both of these are referring to, but I added elements for both.
There are comments for Desert Resort and Undella Bay to become routes. I've still added elements for both dungeons for now.

### CODE REVIEW

**Comment by RedSparr0w** [comment]
I haven't had a chance to look at all the changes yet,
But if you are updating the map image `.png` you also need to update the tiled map so it can be reproduced/edited.

**Comment by HLXII** [comment]
I got the updated map from anapple. Not sure if they commited the tiled map, since the .tmx file on the branch wasn't updated either. https://github.com/anapple96/pokeclicker/tree/UnovaMap Here's the branch I got it from.

**Comment by anapple96** [comment]
Delay this PR. There's some changes going up that'll require a remake of the base and SVG map

**Comment by HLXII** [comment]
Closed due to major refactoring of routes by Apple. They'll handle the SVG implementation.

**Pull request closed without merging**
