### PR TITLE
Hisui Trainer Sprite

### PR DESCRIPTION
**Pull request by Qwertypop04**
From Pokemon Showdown. Currently lacking sprite for Volo (Ginkgo).

### CODE REVIEW

**Review by osherwott — COMMENTED** [review]
Question: There is currently a Ginkgo Volo on Showdown. Was that there when you made this PR or are you waiting on something else?

**Comment by Someonealive-QN** [comment]
> Question: There is currently a Ginkgo Volo on Showdown. Was that there when you made this PR or are you waiting on something else?

he's waiting for me to get the permission from the person who made it

**Comment by Qwertypop04** [comment]
We now have a Volo (Ginkgo) sprite, so this is ready for review

**Review by Jaaslet — APPROVED** [review]
Looks good. Thanks for the PR

**Pull request merged**
