### PR TITLE
Hoenn changes

### PR DESCRIPTION
**Pull request by RedSparr0w**
**Note:**
> This PR is being merged into the `Hoenn` branch

- Made Hoenn not accessible (`MAX_REGION_AVAILABLE`)
- Couple of small fixes made due to latest changes in `v1.0.2` or `v1.0.3`

### CODE REVIEW

**Comment by RedSparr0w** [comment]
😩 Damnit, thought this was merged so i reset the branch lol, guess I should redo the changes

**Comment by Ishadijcks** [comment]
Yeah I was wondering, this doesn't look right :p

**Comment by RedSparr0w** [comment]
I'll fix it up quickly and let you know when its done.
I've disabled being able to access Hoenn, so once this is merged we can add it to the develop branch to avoid future conflicts.

**Comment by RedSparr0w** [comment]
Sweet, this should be good for merge into `Hoenn` branch and then `Develop`

**Pull request merged**
