### PR TITLE
Dungeon pokemons level adjustment

### PR DESCRIPTION
**Pull request by Symi001**
Dungeon pokemon now use the routeLevel function to get their level, it should significantly boost the xp of the pokemon in dungeons.

### CODE REVIEW

**Comment by Symi001** [comment]
Followed the advice of jk. This gives a bit more exp even to older dungeons. Tested with several dungeons (in Kalos and Kanto) and it seemed alright, but I'll let you see if you think it's a bit too much exp :)

**Comment by RedSparr0w** [comment]
Should we just be removing `Dungeon.level` entirely?

Doesn't really seem to be used elsewhere, especially if we can just use the route level as a default?

**Comment by Symi001** [comment]
> Should we just be removing `Dungeon.level` entirely?
> 
> Doesn't really seem to be used elsewhere, especially if we can just use the route level as a default?

Should be alright now, I got rid of it, I still have a question, what do you think about it: should I create a function to get a dungeon level as it's already the same call in three places ?

**Comment by RedSparr0w** [comment]
> Should be alright now, I got rid of it, I still have a question, what do you think about it: should I create a function to get a dungeon level as it's already the same call in three places ?

👍 Yeah that's probably a good idea, instead of us calling the same set of functions multiple times.

**Comment by Symi001** [comment]
Should be all good now, sorry for the delay ^^"

**Review by RedSparr0w — APPROVED** [review]
Nice work! Thanks for the PR 👍

**Pull request merged**
