### PR TITLE
Update PokedexHelper.ts

### PR DESCRIPTION
**Pull request by mog-kupo**
Small change to show event Pokemon in the pokedex.

### CODE REVIEW

**Review by LuqDragon — COMMENTED** [review]
now need to change the way to show them 😉 
image

**Review by anapple96 — COMMENTED** [review]
Can't see an use for this, as we're moving the rest of the eventmons to `x.1` soon:tm:;

**Comment by mog-kupo** [comment]
> Can't see an use for this, as we're moving the rest of the eventmons to `x.1` soon:tm:;

If that change is coming in the next update that's fine... Until then it's a quick fix to see the event mons.

**Comment by RedSparr0w** [comment]
Updated to show `-` IDs as `???`

**Review by RedSparr0w — APPROVED** [review]
Thanks for the PR! 👍

**Pull request merged**
