### PR TITLE
Updating dependencies - work in progress

### PR DESCRIPTION
**Pull request by erzads**
@Aegyo here =D

### CODE REVIEW

**Comment by erzads** [comment]
Currently trying to solve this issue:
```Uncaught (in promise) TypeError: Unable to process binding "template: function(){return { name:'otherItemTemplate',data:'Protein'} }"
Message: Unable to process binding "tooltip: function(){return {
        title:ItemList[$data] ?`<u>${ItemList[$data].displayName}</u><br/>${ItemList[$data].description || ''}`:'',trigger:'hover',placement:'top',html:true,boundary:document.getElementById('showItemsModal'),} }"
Message: Cannot read properties of undefined (reading 'config')
    at update (script.min.js?v=0.10.0:26362:29)
    at a.$.l (knockout-latest.js:79:379)
    at Function.yd (knockout-latest.js:55:359)
    at Function.zd (knockout-latest.js:55:45)
    at Function.ha (knockout-latest.js:54:384)
    at a.o.a.$ (knockout-latest.js:52:147)
    at knockout-latest.js:79:366
    at Object.D (knockout-latest.js:11:52)
    at p (knockout-latest.js:78:408)
    at k (knockout-latest.js:76:170)

**Comment by RedSparr0w** [comment]
I'd be very surprised if updating bootstrap to `v5.x.x` doesn't require a ton of changes to the html also.

**Comment by erzads** [comment]
Perhaps, but it's a nice exercise.

I somewhat found out the issue.
The GameController has a function responsible of creating tooltips based on Knockout elements with the tooltip property.

There are 2 methods:
- init: this seems to be working propertly. Is gets the tooltip property value, resolves it and creates the tooltip.
- update: here is the issue. There is a property that's coming as null. I am still trying to understand why. (`$(element).data('bs.tooltip');`)

**Comment by erzads** [comment]
@Aegyo @RedSparr0w  could you take a look at this PR? If it makes sense? I am able to run everything and hasn't noticed anything out of the ordinary, but I am not sure if there is some kind of acceptance test. (I just ran "npm test").

**Comment by Aegyo** [comment]
Did you check through the  [bootstrap migration page](https://getbootstrap.com/docs/5.0/migration/)?
Some things that jump out at me from there are nested tables (I think we do that in Settings?), thead classes, close button, and a bunch of the utility classes for margin and padding.

Do you see any improvement in the modal lag you were seeing?

You also have a bunch of changes in the docs folder, we'll want you to reset those changes before merging.

**Comment by erzads** [comment]
The lag when triggering a modal is still happening no mobile.
I also noticed some minor UI issues like some elements overflowing their containers.

This branch could be used for updating bootstrap just for the sake of keeping it updated.

**Comment by RedSparr0w** [comment]
Haven't had a chance to look through the code changes yet, but from a quick look around the UI I noticed the following places have issues:

Save selector, saves are no longer rounded
Multiple modals can no longer stack
Underground not visible
Farm - Berries/mulch text misaligned
Farm - Plant/harvest all button separated now
Farm - Berrydex not displaying correctly
Hatchery (main display)
Hatchery modal (pokemon, eggs, fossils)
Hatchery helpers progress
Dungeon timer (when showing both currency rows)
Pokémon attack tooltip no longer works
NPCs in towns no longer show modals
No spacing between notifications

**Comment by erzads** [comment]
@RedSparr0w thanks! I was aware of some of those. It would be great to have some more hands on the matter. Perhaps some devs familiar with bootstrap. I am gonna ask around on Discord.

**Comment by erzads** [comment]
@RedSparr0w I am gonna try and list your points as issues to be solved.

- [ ] Save selector, saves are no longer rounded
This one I am not so sure. What's supposed to be rounded?
Current production version:
Screenshot from 2022-10-31 19-15-30

- [ ] Multiple modals can no longer stack
Can you point me to a place where multiple modals could be opened?
- [ ] Underground not visible
- [ ] Farm - Berries/mulch text misaligned
- [ ] Farm - Plant/harvest all button separated now
- [ ] Farm - Berrydex not displaying correctly
- [ ] Hatchery (main display)
- [ ] Hatchery modal (pokemon, eggs, fossils)
- [ ] Hatchery helpers progress
- [ ] Dungeon timer (when showing both currency rows)
- [ ] Pokémon attack tooltip no longer works
- [ ] NPCs in towns no longer show modals
- [ ] No spacing between notifications

**Comment by erzads** [comment]
I am pushing a bunch of fixes and working on some more that I found.

- [ ] Multiple modals can no longer stack
That's by design on BS5. I am gonna look for a workaround like this https://www.cssscript.com/nested-bootstrap-5-modal/

- [ ] Quest panel is misaligned 
Screenshot from 2022-11-01 14-45-29

- [ ] Start menu is not opening
This one I spent some time but still couldn't figure out. Basically, when you click the dropdown button it was supposed to add the "show" css class to it, but it's not happening.

**Comment by RedSparr0w** [comment]
### Save selector, saves are no longer rounded
> This one I am not so sure. What's supposed to be rounded?

👍 Yeah, It must just be my default theme taking over and making things rounded.
image

### Multiple modals can no longer stack
> Can you point me to a place where multiple modals could be opened?

Only places I can think off the top of my head is Berrydex, Pokédex and Safari Zone.

**Comment by erzads** [comment]
@RedSparr0w  @Aegyo Would you guys take a look at the changes? I combed through the entire game (I think so) and fixed everything I found.
The only detected issue remaining is that I had to undo the attack tooltip change I made a while ago. I tried everything I could think of but still couldn't fix it.

Basically, when bootstrap/popperjs tries to show a tooltip if checks if the 'title' property is a function. If it is, it calls it with 'this' as an arg. I believe this is new behavior.
Passing 'this' makes knockout complain about receiving a value. 
```
knockout-latest.js:50 Uncaught Error: Cannot write a value to a ko.computed unless you specify a 'write' option. If you wish to read the current value, don't pass any parameters.
    at e (knockout-latest.js:50:350)
    at TemplateFactory._resolvePossibleFunction (bootstrap.esm.js:3685:40)
    at TemplateFactory._setContent (bootstrap.esm.js:3659:20)
    at TemplateFactory.toHtml (bootstrap.esm.js:3622:12)
    at Tooltip._createTipElement (bootstrap.esm.js:3998:51)
    at Tooltip._getTipElement (bootstrap.esm.js:3991:23)
    at Tooltip.show (bootstrap.esm.js:3889:22)
    at eval (bootstrap.esm.js:4197:14)
```
Screenshot from 2022-11-02 19-36-35

**Comment by Jaaslet** [comment]
I closed this issue, as it's a lot of work for little gain, and none of us reviewers will have time to look at it

**Pull request closed without merging**
