### PR TITLE
Encounter modal fixes

### LINKED ISSUE #5418: [Bug]: Pokemon Route Viewer does not scroll
### Confirmations

- [X] I have searched open and closed issues for any existing report of my issue

### What happened?

Tried using the Pokemon route viewing option and found that it did not scroll up or down to show all the available Pokemon. I am playing in my browser on mobile.

### What did you expect to happen?

Was hoping to scroll up and down to view all the available Pokemon in a route. The Pokerus status appears to work fine at displaying how many EVs a Pokemon has but the some Pokemon entries get cut off at the bottom due to inability to scroll. It shows fine if there are less than 10 Pokemon available on a route and even shows if its a Roaming Pokemon.

### Steps to Reproduce

1. Go to any route with more than 10 Pokemon that inhabit it 
2. Click on the Pokemon Radar icon 
3. Attempt to scroll on any portion of the page

### What operating system are you using?

Android

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

_No response_

### Additional Information

_No response_

### LINKED ISSUE #5419: [SUGGESTION]: Unlocked lock icon for dungeon loot viewer
### Current Behavior

Requirement lock never disappears.
image

### Improved Behavior

Requirement lock should change to "Unlocked lock" icon when the requirement is met. This keeps the hint visible that there is a requirement, but with the addition that you are eligible to receive the drop.

### Reason for change

Intuitive behaviour

### Detailed Description

Add unlocked lock icon and show that when the requirement is met.

### LINKED ISSUE #5420: [SUGGESTION]: Add a way to scroll when checking the availables pokemons on a route
### Current Behavior

If there are to much pokemons availables on a route, you can't scroll to see the lowers ones. 

Road info current

### Improved Behavior

Add a way to scroll down to see all the pokemons, like for the pokedex.

### Reason for change

Because it makes this new functionality not working completely. 

### Detailed Description

Something like this
Road info example

### PR DESCRIPTION
**Pull request by Sinonea**
## Description

Fixes the bugs of my feature "Encounter Modal".

## Motivation and Context

Fixes #5418 
Fixes #5419
Fixes #5420 

Two bugs were found by the community and I thank them for their feedback!

I apologize for the inconvenience caused and I got to work straight away to correct them!

I thank @EatPant2nd for reporting the bugs found to me since I am not comfortable with the public discord.

The two bugs found are:
- No scrolling for both modals
- The lock for loots in dungeons was still present even if the conditions were met to obtain it

Both bugs have been fixed via this PR.

Thank you and sorry again.

Update 15/07 : remove the shadow status from route modal to avoid players think there are shadows on the routes.

## How Has This Been Tested?

I looked at the two modals to check if the scroll was present and I checked the lock on a part where the condition was met (no more lock) and when the condition was not yet met (lock still present).

@EatPant2nd also checked. Thanks to them !

## Screenshots (optional):

Scrolls :
image
image

Unlocked :
image
image

Locked : (no changes)
image
image

Shadow (Update 15/07) :
[Before]
image
[After]
image

## Types of changes

- Bug fix (Encounter modal feature)

### CODE REVIEW

**Comment by AevitasDragonkin** [comment]
Was wondering, I've also spotted some screenshots in Discord where a quest requirement will not correctly show the requirement. Is this also resolved with that?

image
image

**Comment by Sinonea** [comment]
Normally yes. The lock image is showed only where the requirements aren't completed in the fixes. On the quest, the requirements are completed to obtain the Great Spoon, so no lock. Eat Pant had showed me your bug ! Thank for feedback !

**Review by CypherX — APPROVED** [review]
Looks good. I fixed two small things I noticed while testing

**Comment by Sinonea** [comment]
Thanks for the fixes @CypherX ! And thanks for the merge !

**Pull request merged**
