### PR TITLE
[FIX] Obtaining key item by badge requirement

### PR DESCRIPTION
**Pull request by PixLSteam**
Reloading the page while on certain "Gym Badge obtained" popups would prevent the player from gaining the corresponding key items. This change should add the item silently while delaying the item popup.
I was only able to test the Safari ticket, not the Shard case.
I'm not sure if an update function for broken saves is needed, but feel free to request it.

### CODE REVIEW

**Comment by Askellown** [comment]
can confirm after loading an old challenge save this also applies to Gio and the shard case

**Review by RedSparr0w — APPROVED** [review]
👍 Changes look good, thanks for the PR!

**Comment by RedSparr0w** [comment]
> I'm not sure if an update function for broken saves is needed, but feel free to request it.

Yeah, it's probably worth adding one, just in case any people not in the Discord encountered this problem too, and may not have ever noticed 😅

**Comment by PixLSteam** [comment]
I implemented the update function.

**Comment by RedSparr0w** [comment]
Looks great thanks 👍

**Pull request merged**
