### PR TITLE
Fixed computed not being refreshed.

### PR DESCRIPTION
**Pull request by Vodovik**
@Jaaslet this should be part of the next releases a it fixes a bug : )

### CODE REVIEW

**Comment by Jaaslet** [comment]
It would make it easier to review if you explain what bug

**Comment by Malayena** [comment]
> It would make it easier to review if you explain what bug

The hour was calculated once on start-up and never refreshed due to new Date() not being observable. The game needed to be restarted to show the correct new moment of the day.
Using GameHelper.currentTime(), which is observable, fixes that.

**Comment by Vodovik** [comment]
sorry, i created the bug on discord. The new time of day icon isn't refreshed when you enter a new time part, like day => dusk, dusk => night, .. now it should be doing what malayena just explained : ) (and it is in my tests, the refresh only happens once every minute, so if you time travel to test it, you'll need to wait 1 min at least : ))

**Review by Jaaslet — APPROVED** [review]
Looks good. Thanks for the PR

**Pull request merged**
