### PR TITLE
The Castform Shuffle

### PR DESCRIPTION
**Pull request by Ultima1990**
Base Castform removed from route 119, now a boss in the Weather Institute. Requires at least one Weather Institute clear so that players will always have to defeat Aqua Admin Shelly at least once.

The other Castform forms remain on 119 but now require owning base Castform in addition to the weather requirement.

Removed fog from the possible weathers for Castform (snowy). Don't know why that was there.

Additionally a small bug fix, added Weather Institute to the requirements for route 120.

### CODE REVIEW

**Comment by RedSparr0w** [comment]
> Removed fog from the possible weathers for Castform (snowy). Don't know why that was there.

I think fog was there as that is how it can also appear in Pokémon GO IIRC

**Comment by amative1** [comment]
That is correct, it's a POGO addition due to the possibility of lack of snow in tropical areas of the world (since it's tied to IRL weather)

**Comment by Ultima1990** [comment]
Fair enough. The fog's back.

**Review by RedSparr0w — APPROVED** [review]
Looks good 👍 Thanks for the PR!

**Pull request merged**
