### PR TITLE
Replace Johto League sprites

### PR DESCRIPTION
**Pull request by Ultima1990**

### CODE REVIEW

**Comment by Jaaslet** [comment]
Credits?

**Comment by DorkyDelphox** [comment]
> Credits?

They're the HG/SS sprites so, Game Freak? :b

**Comment by Jaaslet** [comment]
> They're the HG/SS sprites so, Game Freak?

Oh, easy! No need to support a small indie company

**Review by Jaaslet — APPROVED** [review]
Looks good. Thanks for the PR

**Pull request merged**
