### PR TITLE
Fill Queue Button

### PR DESCRIPTION
**Pull request by Mephistic**
## Problem

In later regions, it takes dozens of clicks to fill your hatchery queue for attack grinding.

## Solution

This PR adds a "Fill Queue" button to the hatchery that will attempt to fill the hatchery queue with all breedable pokemon that match the current filters, prioritized by sort order.

This option only becomes available once the player has at least 16 queue slots because I felt that was the point where the needed clicks started getting annoying.

Screen Shot 2021-06-13 at 1 03 28 PM

## Related Issues

https://github.com/pokeclicker/pokeclicker/issues/1179
https://github.com/pokeclicker/pokeclicker/issues/1405

### CODE REVIEW

**Comment by IdlerDude** [comment]
I am happy to see that this issue is still open. I finally broke down and got a github id just to add this suggestion, but it's already here :) I play this game basically as it was designed - no mouse macros, no auto-clickers, etc... The amount of "required" clicking in the rest of the game is warranted, focused, and the player has discretion when and if they want to do it. This is not the case for filling up the hatchery queue. It is a mindless task of placing the desired eggs into the queue. There is nothing special from the first to last click EVERY time a person wishes to fill the queue. This is why a "Fill Queue" button greatly increases the playability of the game. In my mind, it is a one time replacement of 16 or 32 continuous clicks. It is not a request to do it on a continual basis. 

If the devs wish, they can optionally tie this to some event or quest line that requires players to fork out money or effort to show they know how to play and this rewards them with some benefit.

One factor to consider is that there is a fairly strong rule to not talk about automation tools in discord. The lack of some kind of "Fill Queue" button will push even die-hards like myself to look for one... it's only a matter of time before I get fed up of continually doing 32 continuous clicks to fill up the queue. Should the queue increase in size,   without such a feature... that would just simply be crazy.

A minor point: As I stated in 1724 - this issue has nothing to with that one. My humble opinion of course.

**Comment by JapuDCret** [comment]
bump

**Comment by Ultima1990** [comment]
> bump

Don't do that.

**Comment by amative1** [comment]
Per Hatchery Helpers ( #2053 ), no longer necessary.

**Pull request closed without merging**
