### PR TITLE
"Mimic" Encounters and Johto Dungeon Loot

### PR DESCRIPTION
**Pull request by jk13pclick**
Forgot to do this, allows for "Mimic" encounters. Also adds better loot to the new Johto Dungeons

### CODE REVIEW

**Comment by RedSparr0w** [comment]
Love it, but it seems to generate a couple oddities 😅
image

**Comment by jk13pclick** [comment]
I suppose I should have tested this after I added all the loot back into the game 😅. I'll have a fix shortly

**Comment by jk13pclick** [comment]
Should be good now. 2AM coding mistake fixed 😄

**Review by RedSparr0w — APPROVED** [review]
Looks good, thanks for the PR! 👍

**Pull request merged**
