### PR TITLE
Added day cycle display next to the weather to help with day cycle de…

### PR DESCRIPTION
**Pull request by Vodovik**
…pendent features (lycanroc, alcremies, umbreon, ..)

Probably made plenty of mistakes, I'm rather clueless as to how JS and TS work. Any help and criticism is welcome.

### CODE REVIEW

**Comment by Vodovik** [comment]
image
looks like this btw : )

**Comment by Jaaslet** [comment]
Where are the images taken from? Do they need to be in the credits?

**Comment by DraKay** [comment]
Oficial pokeclicker image database aka DraKay drawing

**Comment by Someonealive-QN** [comment]
Drak made them. I think they probably should be in credits for her

**Comment by Vodovik** [comment]
Btw, jaas, the colors were chosen to match dawn, dusk, sun and moon evolution stones.

**Review by Jaaslet — APPROVED** [review]
Looks good. Thanks for the PR.
If you (or anyone else) want to do a bit of refactoring, we could use DayCycle.currentDayCyclePart() for stuff like the battle cafe or evolution stones, to make it harder to make mistakes in the code.
But it does not have to be in this PR, so i will merge this

**Pull request merged**
