### PR TITLE
Removing Shuckle as Dungeon Boss in Hall of Origin

### PR DESCRIPTION
**Pull request by Razorflamekun**
## Description

Shuckle is only listed as being able to be found on Route 224 with Emerald inserted into the DS.  Therefore, I would like to remove Shuckle as a Dungeon Boss in Hall of Origin.

## Motivation and Context

My motivation is this isn't Canon.

## Types of changes

-Dungeon Boss Change

### CODE REVIEW

**Comment by wormania** [comment]
Wouldn't "canon" be to have absolutely nothing in this dungeon apart from the Arceus boss? _Everything_ here is a fabrication to make it fit with how dungeons work in this game

**Comment by Razorflamekun** [comment]
> Wouldn't "canon" be to have absolutely nothing in this dungeon apart from the Arceus boss? _Everything_ here is a fabrication to make it fit with how dungeons work in this game

Yes, that is true, however, the developers of this game have made it clear that they don't want single dungeon bosses that are Legendary.  In terms of the actual dungeon theme, it seems as though the bosses are all Normal type, while Shuckle is not.

**Comment by Qwertypop04** [comment]
Needs a boss to replace it.

**Comment by Razorflamekun** [comment]
Added Staraptor as a replacement boss.

**Review by Qwertypop04 — APPROVED** [review]
Looks good, thanks for the PR!

**Pull request merged**
