### PR TITLE
Add some towns and add some extensions to Hau'oli

### PR DESCRIPTION
**Pull request by Ultima1990**
Added Iki Town Outskirts, AKA the player's house in SMUSUM. It is now the home town. Iki Town now requires route 1.
Added Professor Kukui's Lab. Requires route 1 outskirts. Might be useful for something at some point.
Added Roadside Motel. Requires Alola Champion. Will be part of UB probably. Very shit image, couldn't find anything better.
The remaining 2 houses have become extensions of Hau'oli City.

### CODE REVIEW

**Comment by Qwertypop4** [comment]
Iki Town Outskirts should be renamed to Hau'oli Outskirts, since that's what it is actually called. You naming it Iki Town Outskirts reminded me lol

**Comment by Ultima1990** [comment]
> Iki Town Outskirts should be renamed to Hau'oli Outskirts, since that's what it is actually called. You naming it Iki Town Outskirts reminded me lol

We already have a Hau'oli Outskirts. Route 1 Hau'oli Outskirts. So changed it up for the town.

**Review by RedSparr0w — APPROVED** [review]
Looks good, thanks for the PR! 👍 

Do we need to change the startingtown in GameContants? or leave it as is?

**Comment by Ultima1990** [comment]
> Looks good, thanks for the PR! 👍
> 
> Do we need to change the startingtown in GameContants? or leave it as is?

We do need to do that. I do believe I already did that though.
IkiTownOutskirtsConstants

**Pull request merged**
