### PR TITLE
Observable fixup #2

### PR DESCRIPTION
**Pull request by jk13pclick**
Might want to consider adding an increment observable to the actual gainPokeballs method. Maybe want to split up observables for "Bought" and "Obtained"

### CODE REVIEW

**Comment by RedSparr0w** [comment]
> Might want to consider adding an increment observable to the actual gainPokeballs method.

Yeah, I think it's probably better to add it to `gainPokeballs` at this point instead 😅 
Otherwise chances are it will be forgotten again later.

**Comment by jk13pclick** [comment]
While I was at it with the observables I fixed up #1354. Up to you if you want the HarvestBerryQuest to track Obtained Berries or Harvested Berries

**Comment by RedSparr0w** [comment]
Branch seems to be failing now after updating to from main

**Comment by jk13pclick** [comment]
All good now

**Review by RedSparr0w — APPROVED** [review]
Thanks for the PR!
Looks good 👍

**Pull request merged**
