### PR TITLE
Added snorlax as temp battle

### PR DESCRIPTION
**Pull request by Jaaslet**
Snorlax is now an overworld sprite temp battle. Kanto has two. For each to go away, you need to beat it, and capture any of them.

- [x] Add snorlax
- [x] Add CaptureSpecificPokemonRequirement
- [x] Make sure wild temp battles can be caught
- [x] Make sure snorlax shows up on map before it's unlocked

### CODE REVIEW

**Review by RedSparr0w — APPROVED** [review]
Looks good to me, thanks for the PR! 👍

**Comment by RedSparr0w** [comment]
Just a couple of things before merging:

Are the Snorlax supposed to be a 0% catch rate with base Poké Balls?
Are they not supposed to disappear once defeated?
Is the only way to access route 16 by defeating the Snorlax, can you not leave Snorlax undefeated and access it from route 17? _(been awhile since I've played RBY)_
Are we able to grey/darken the images until they are able to be challenged?

**Comment by Jaaslet** [comment]
> Are the Snorlax supposed to be a 0% catch rate with base Poké Balls?

No, that is a bug. I should look at that, before we merge.

> Are they not supposed to disappear once defeated?

They are suppose to disappear when defeated AND caught. Else the pokedex might not be possible

> Is the only way to access route 16 by defeating the Snorlax, can you not leave Snorlax undefeated and access it from route 17? _(been awhile since I've played RBY)_

I just followed the old requirements. Basicly just moved everything over once. But i am not sure it's correct.

> Are we able to grey/darken the images until they are able to be challenged?

I can look into that

**Comment by Jaaslet** [comment]
Ready for review.
You have fixed the requirements. I have now updated it to the newest version, done some cleanup and added the locked mapoverlay.
I have no idea why, but the catchrate works now... Might have happened in some other PR, or during some of my cleanup... No idea

**Review by RedSparr0w — APPROVED** [review]
Works great, thanks for the PR! 👍

**Pull request merged**
