### PR TITLE
Stone Fix

### PR DESCRIPTION
**Pull request by Ultima1990**

### CODE REVIEW

**Comment by Aegyo** [comment]
Any others?

```
$ grep -n "StoneType.None" ./src/scripts/pokemons/PokemonList.ts
9270:        'evolutions': [new StoneEvolution('Bonsly', 'Sudowoodo', GameConstants.StoneType.None)],
9289:        'evolutions': [new StoneEvolution('Mime Jr.', 'Mr. Mime', GameConstants.StoneType.None)],
9308:        'evolutions': [new StoneEvolution('Happiny', 'Chansey', GameConstants.StoneType.None)],
9626:        'evolutions': [new StoneEvolution('Mantyke', 'Mantine', GameConstants.StoneType.None)],
12139:        'evolutions': [new StoneEvolution('Minccino', 'Cinccino', GameConstants.StoneType.None)],
12876:        'evolutions': [new StoneEvolution('Lampent', 'Chandelure', GameConstants.StoneType.None)],
14499:        'evolutions': [new StoneEvolution('Doublade', 'Aegislash', GameConstants.StoneType.None)],
15511:        'evolutions': [new StoneEvolution('Charjabug', 'Vikavolt', GameConstants.StoneType.None)],
15563:        'evolutions': [new StoneEvolution('Crabrawler', 'Crabominable', GameConstants.StoneType.None)],
16139:        'evolutions': [new StoneEvolution('Steenee', 'Tsareena', GameConstants.StoneType.None)],
17036:        'evolutions': [new StoneEvolution('Poipole', 'Naganadel', GameConstants.StoneType.None)],
17122:        'evolutions': [new StoneEvolution('Meltan', 'Melmetal', GameConstants.StoneType.None)],
```

**Comment by RedSparr0w** [comment]
I think these 4 are all happiness evos (Soothe Bell)
```js
9270:        'evolutions': [new StoneEvolution('Bonsly', 'Sudowoodo', GameConstants.StoneType.None)],
9289:        'evolutions': [new StoneEvolution('Mime Jr.', 'Mr. Mime', GameConstants.StoneType.None)],
9308:        'evolutions': [new StoneEvolution('Happiny', 'Chansey', GameConstants.StoneType.None)],
9626:        'evolutions': [new StoneEvolution('Mantyke', 'Mantine', GameConstants.StoneType.None)],
```
And not sure about these 2:
```js
12139:        'evolutions': [new StoneEvolution('Minccino', 'Cinccino', GameConstants.StoneType.None)],
12876:        'evolutions': [new StoneEvolution('Lampent', 'Chandelure', GameConstants.StoneType.None)],
```
And these aren't available yet AFAIK:
```js
14499:        'evolutions': [new StoneEvolution('Doublade', 'Aegislash', GameConstants.StoneType.None)],
15511:        'evolutions': [new StoneEvolution('Charjabug', 'Vikavolt', GameConstants.StoneType.None)],
15563:        'evolutions': [new StoneEvolution('Crabrawler', 'Crabominable', GameConstants.StoneType.None)],
16139:        'evolutions': [new StoneEvolution('Steenee', 'Tsareena', GameConstants.StoneType.None)],
17036:        'evolutions': [new StoneEvolution('Poipole', 'Naganadel', GameConstants.StoneType.None)],
17122:        'evolutions': [new StoneEvolution('Meltan', 'Melmetal', GameConstants.StoneType.None)],
```

**Review by RedSparr0w — APPROVED** [review]
Looks good, thanks for the PR!

**Comment by JeSuisUnCaillou** [comment]
For people searching these two issues, they were resolved here.
https://github.com/pokeclicker/pokeclicker/issues/1279 and https://github.com/pokeclicker/pokeclicker/issues/1286

Commenting to link the PR to the issues.

**Pull request merged**
