### PR TITLE
Delta Episode

### PR DESCRIPTION
**Pull request by Ultima1990**
Here's what I've been sneakily working on: the Delta Episode.
A subregion of Kalos that is basically Hoenn again. Intended to be a post-kalosleague location that will function as a source for several mega evolutions and the CosplayChus.

Starring:

- The total removal of anything related to Team Aqua and Team Magma. That problem was solved back in the actual Hoenn region.
- Removal of gyms.
- Changing of encounters to ORAS versions. Including all the DexNav exclusives and stuff.
- Creation of the "Mega Challenge" trainer type.
- Addition of Mega Challenges to most dungeons. So hey, you can _fight_ megas. That's fun.
- Changing of route and dungeon requirements to account for the player starting in Slateport instead of Littleroot.
- Dungeons that appear and disappear based on the weather. I'm sure everyone will love this one.

TODO:

- [x] Wait for mega evolution.
- [x] Wait for quest hubs.
- [x] Update function for the new dungeons.
- [ ] Allow Mega Challenges to grant megas. Or mega stones. Or whatever we actually do for mega evolution.
- [x] Ban Kalos roamers from this subregion.
- [ ] Questline for mega Hoenn starters.
- [x] Questline for primal Kyogre/Groudon.
- [ ] Questline for mega Latias/Latios.
- [ ] Questline for mega Big Snek. <-- THE MAIN QUEST
- [ ] Maybe questline for mega Metagross? (fight Steven Stone)
- [x] Sprite for Street Thug
- [x] Sprite for Mysterious Sisters (awaiting source confirmation on Hex Maniac (kalos) and Fairy Tale Girl sprites).
- [ ] Add the CosplayChus and come up with some fun way to obtain them.

### CODE REVIEW

**Comment by Qwertypop04** [comment]
Would it be possible to make it a Hoenn subregion that only unlocks after Kalos champ?

**Comment by Ultima1990** [comment]
> Would it be possible to make it a Hoenn subregion that only unlocks after Kalos champ?

Why?

**Comment by Qwertypop04** [comment]
Because it's, well, Hoenn

**Comment by Qwertypop04** [comment]
Idk imo it just makes less sense having the second Hoenn being not in Hoenn

**Comment by Ultima1990** [comment]
> Because it's, well, Hoenn

But ORAS are gen6 games. So it makes more sense for it to be a gen6 subregion.

Also I am utterly baffled by these linebreak complaints.

**Comment by Qwertypop04** [comment]
Just wasn't sure if it was actually possible or not. Although, Sevii is being added as a subregion of Kanto instead if Hoenn, so the inconsistency is a little weird

**Comment by Ultima1990** [comment]
It is possible, yes. Especially now that I can hardcode routehealth.

What matters here is when the content is relevant. Sevii is being added as a Kanto subregion because it has Kanto content. Content you go to during Kanto. Delta Episode is Kalos content. Content you go to during Kalos.

**Comment by CorgiOnNeptune** [comment]
Hey 2 questions, for Delta Episode are you wanting to keep the unlockable Megas to ones that were released in ORAS and keep the original set of Megas to the main Kalos region? Or just throw them all into Delta as Megas become ready? 

And what’s the quest hub feature you’re waiting on? 

Just asking so I can brainstorm questlines and maybe mechanic ideas.

**Comment by Jaaslet** [comment]
> And what’s the quest hub feature you’re waiting on?

We have some (many) optional quests planned. And to not fill up the UI too much, we want to add a place where you accept quests. So if players don't want to look at 5 quests at a time, they can only accept one at a time. That is basicly it. Main quests will still be started automatically.

> are you wanting to keep the unlockable Megas to ones that were released in ORAS and keep the original set of Megas to the main Kalos region?

I think the Delta region is only going to contain the Megas listed in the PR description

**Comment by CorgiOnNeptune** [comment]
> We have some (many) optional quests planned. And to not fill up the UI too much, we want to add a place where you accept quests. So if players don't want to look at 5 quests at a time, they can only accept one at a time. That is basicly it. Main quests will still be started automatically.

Ok perfect, that’s what I imagined it would be. Just to reduce clutter for extra quests that aren’t the refreshing quests. 

> I think the Delta region is only going to contain the Megas listed in the PR description

👍👍Maybe the Mega Challenges can be used to unlock some of the other Hoenn Megas, but I have some ideas I’ll flesh out more.

**Comment by Ultima1990** [comment]
> > We have some (many) optional quests planned. And to not fill up the UI too much, we want to add a place where you accept quests. So if players don't want to look at 5 quests at a time, they can only accept one at a time. That is basicly it. Main quests will still be started automatically.
> 
> Ok perfect, that’s what I imagined it would be. Just to reduce clutter for extra quests that aren’t the refreshing quests.
> 
> > I think the Delta region is only going to contain the Megas listed in the PR description
> 
> 👍👍Maybe the Mega Challenges can be used to unlock some of the other Hoenn Megas, but I have some ideas I’ll flesh out more.

The Mega Challenges _will_ be used to unlock other megas. Not necessarily Hoenn megas. Just things that fit well.

So far I have:
Beedrill in Petalburg Woods (doesn't have to be Beedrill, but I do want it to be a bug)
Mawile and Sableye in Granite Cave
Manectric in New Mauville
Camerupt in Fiery Path
Salamence in Meteor Falls
Banette in Mt. Pyre
Glalie in Shoal Cave
Gallade in Victory Road

**Comment by Ultima1990** [comment]
I've just gone through and done a big ol' conflict resolution on this PR. Twas a giant mess, I thought it'd be kind to take care of it. While I'm here I'm gonna do a full outline of my intentions with this, in case anyone ever picks it up and in case that person cares about what I wanted this to be.

**The Delta Episode subregion**
The subregion is intended to be a post-Kalos league version of Hoenn that mostly acts as a source for megas, once megas are actually implemented. The routes and dungeons are supposed to be Kalos 23+ difficulty, and are updated with the ORAS post-migration event encounters. The player is intended to progress through the whole region again, but this time the player has arrived in Slateport and the requirements are changed to match this. It is currently implemented as a subregion of Kalos, because it is based on ORAS which is gen6 just like Kalos and also it made more sense to me to travel from Kalos to Hoenn than from Hoenn to Hoenn. Update function for the dungeons and tempbattles probably don't point at the correct indexes anymore, someone's gonna have to fix that.

**The Delta Episode main quest**
The main quest, called Delta Episode just like the subregion (no it's not confusing what are you talking about?) is basically just the ORAS Delta Episode storyline, with some small changes at the beginning. It is not even close to fully imlemented.
The questline is picked up at the Kalos quest board, starting with some slightly ominous words from Birch. Something bad going on maybe? So of course you drop everything and use the subregional travel to get to Slateport, where you ask the first person you meet for information.
That first person is of course Reporter Gabby, the Hoenn roamer NPC. Gabby tells you that she's not reporting on roaming Pokémon anymore, but she does tell the player about the new Pokémon that have shown up in the region (migration event). Nothing else weird going on. If you have more questions go ask Birch. So that's of course what you do.
Birch is surprised, the message was not supposed to sound ominous lol, just about some super duper cool unique meteor shower that you should totally go see with a friend. Also he points out that there's new quests on his quest board.
This is where I point out that May is the confirmed PokéClicker canon rival in Hoenn, and the friend for the meteor shower. In a long long ago discussion among the devs we decided to split the rivals that are just gender swapped player characters evenly. There's 2 of them, the gen3 one and the gen6 one, so it was easy. After what basically amounts to a coin flip May became the Hoenn rival and Calem the Kalos rival. Unless that decision has since been overturned? IDK, but it's easily changed regardless.
Anyway, that's where the main quest currently ends. There's some convos and some tempbattles against the aqua and magma admins. Didn't get very far with implementing it. But like I said, it's just the ORAS Delta Episode story. In the end, the grand reward is of course Mega Rayquaza, which doesn't officially have a mega stone but one could just invent the Green Orb for this.

**The Missing Primals**
The one that's fully implemented. Except, of course, the bit where it rewards the mega at the end. Cuz no mega yet.
I mostly decided to do weather stuff with this, while also clearing up some weird stuff because why not.
Like every other Delta Episode "side quest" this starts from the board at Delta Littleroot. It's a message from the weather institute.
They have lost track of Kyogre and Groudon, which they don't like because they can cause massive weather issues so the weather scientists like to know where they are. The first step is investigating the Cave of Origin where they used to live.
In Sootopolis you find out that Kyogre and Groudon have indeed left the cave, and Exploud got left behind. This makes Exploud very sad, and it makes this known by making a whole lot of noise. You see, way back in the day Exploud was added to CoO because we just needed a filler mon. Also back then normal types were extra tanky so _evil laugh_. But while building this subregion I decided to retcon in an actual reason: Exploud is actually Kyogre and Groudon's very bestest BFF.
The scientists at the weather institute ask you to catch this Exploud. Technically you can catch any Exploud, but the quest also asks you to clear Delta Cave of Origins a couple times so might as well catch that one while you're there.
Next the scientists ask you to catch some Castforms. Because it's the weather mon, and Kyogre and Groudon are the weather legendaries, so it just fits. Also it's funny because the only place to catch Castform is the Hoenn weather institute. So you go to the Hoenn region to catch Castform at the weather institute and then bring them to the Delta Episode version of that same building.
Then there's the filler bit where you just catch some water and ground types. Yes, this just artificially stretches out the questline. But also it's sort of necessary for the story because the scientists need some time to do science stuff with Castform and Exploud so you need to be away for a bit. Some time needs to pass.
And then the best part: Kyogre and Groudon have moved into Marine Cave and Terra Cave. Using Castform to predict the weather and the movements of Exploud when that weather is going to occur the scientists have found the locations of these caves. And yes, just like in Emerald version these caves only show up in the correct weather. I'm 100% sure that players will absolutely _love_ this and there will be no complaints at all.
The final quest is to just clear these caves. Clearing the caves should of course also reward the actual primals, but that bit's not implemented yet.

**Mega Pokémon**
Speaking of Marine Cave and Terra Cave, mega Pokémon are currently represented by a "Mega Challenge" dungeon trainer that uses the mega as their only Pokémon. They are trainers to prevent the player catching these megas. Defeating them would in some way reward the mega stone. Maybe guaranteed, maybe at a lower chance, IDK. All this with the idea in mind that we would be going the held item route for mega evolution. Primal Kyogre and Primal Groudon are currently Mega Challenge dungeon trainers in their respective caves, and there are also a whole bunch of them scattered across the subregion's dungeons where I thought they'd fit because IMO it's fine that you just find a couple in various locations. There's like 60 megas, you can't make a questline for all of them.

**Mega Lati@s**
This is the only other one that I've really thought about, but only the general outline. In ORAS these mons are just obtained between badges 5 and 6 for free. But we're not doing the badges journey in Delta Episode, that's already happened 3 regions ago. Also giving away a mega legendary for free? Come on now Game Freak. What is this nonsense. So it's time to come up with something new.
The idea is to involve Gabby again. There's a reason I have the player talk to Gabby right at the start. It's basically a little prelude. In this silly little story the player's goal is to get Gabby reporting on roamers again, because you want to find Lati@s. But Gabby can't do her thing without her trusty cameraman Ty, and they've had a falling out. So the story of the questline is to reunite the reporter duo.
That's it. That's all I got. Like I said, just the general outline.

**The other stuff**
Other stuff I also wanted to do questlines for and had put absolutely no thought or work into yet:
Mega Metagross, probably involving a Steven battle.
Mega Hoenn Starters.
Cosplay Pikachu.

**The end**
The end. Bye bye.

**Pull request closed without merging**
