### PR TITLE
Remove forgotten berries

### PR DESCRIPTION
**Pull request by Ultima1990**
They were supposed to get axed. But they didn't. Oops.

### CODE REVIEW

**Comment by dragonkin550** [comment]
I think you still are missing Liechi and Ganlon in Cave of Origin in this PR

**Comment by Ultima1990** [comment]
Thank you very much. If you spot any other ones please let me know.

**Comment by dragonkin550** [comment]
So far as I can see it should remove all remaining gen3+ berries from dungeons

**Review by Jaaslet — APPROVED** [review]
All berries that will be removed by this PR, needs to get removed.
I approve. Thanks for the PR!

**Comment by dragonkin550** [comment]
...I think you'll be annoyed to find out that we still have a few gen3 berries in dungeons.  Annoyed I missed them too even though I thought I checked them all.

Seafloor Cavern - Rabuta
Cave of Origin - Pomeg, Grepa

**Pull request merged**
