### PR TITLE
Gym Leader Images and Background Update

### LINKED ISSUE #1238: [SUGGESTION] Add Gym Leader Images to Gym View
In #1219, I've added some commented-out code in `gymView.html`

```HTML
        <div>
            <!-- TODO: HLXII - Add after all Gym Leader images are formatted correctly
            <div style="position:absolute; left:65%;">
                <img height=80px data-bind="attr:{ src: GymBattle.gym.imagePath }"/>
            </div>
            -->
            <img class="enemy" data-bind="attr:{ src: PokemonHelper.getImage(GymBattle.enemyPokemon(), GymBattle.enemyPokemon().shiny) }" src=""/>
        </div>
```

This will display the Gym Leader sprite during the Gym battle, much like how the Trainer images will appear during Trainer battles. The main issue with this is that currently some of the Gym Leaders do not have good images to display in the view.

I'm currently assuming the Gym Leader images are 80x80 pixels. If this is the case, they will be displayed correctly:
image

If they are smaller, or aren't pixel art at all, it looks bad:

image
Looks slightly blurry due to the image being 64x64.

image
lol.

To fix this, we need to update the Gym Leader images to be 80x80 pixel art for every Gym Leader.

### PR DESCRIPTION
**Pull request by jk13pclick**
Closes #1238 and part of #2156. We should probably decide what to do about more backgrounds before this is merged

### CODE REVIEW

**Comment by RedSparr0w** [comment]
Just double checking, have you run all the images through something like https://tinypng.com/ to minimise the file sizes?

**Comment by zyx-xyzzy** [comment]
It looks like Jagged Pass and Po Town have no background at all set in the current state of the PR? (they were removed from Mansion, but not readded anywhere else)

**Comment by jk13pclick** [comment]
> It looks like Jagged Pass and Po Town have no background at all set in the current state of the PR? (they were removed from Mansion, but not readded anywhere else)

Po Town was a mistake, I wanted to give Jagged Pass the default route background.

**Comment by jk13pclick** [comment]
Closed by #2860 and #2897, so closing this.

**Pull request closed without merging**
