### PR TITLE
Make Kyurem forms available

### PR DESCRIPTION
**Pull request by Ultima1990**
Some opinions needed. Some help also. Consider this a prototype for how it could be done. Basically: Black DNA and White DNA drop as items from Zekrom and Reshriram in Dragonspiral Tower. Can be used to evolve Kyurem, like any old evolution stone item. Thinking ~10% drop, which is why I need a separate dungeon boss held item chance constant. Or separate drop chances for these specific mons, or these specific items. I think dungeon boss might be easier?
Images are very placeholder of course.
Would like to add DNA Splicer key item for flavor. Haven't found what file contains key item unlock conditions.
If this method of obtaining these forms is approved, it could be re used for Necrozma.
Haven't been able to get Kyurem to show up in the evolution stones interface. The stones show up, the mon doesn't. I did give myself Kyurem, it's in my list. I'm sure I forgot something somewhere or messed something up, please point me in the right direction.
NoKyurem

### CODE REVIEW

**Comment by KrushGames** [comment]
i have photoshop, want me to find some dna with design similar to the rest of the sprites and color correct it? i can get it done this weekend if you need

**Comment by Ultima1990** [comment]
> i have photoshop, want me to find some dna with design similar to the rest of the sprites and color correct it? i can get it done this weekend if you need

That would be flippin' hawt. Show me what you got!
Can you make a golden/yellow one and a purple one too? In case we go a similar route with Necrozma.

**Comment by KrushGames** [comment]
so i couldnt find a good one that can be made pixelated ya know, but i have a decent one rn, just finishing the black one. is a decent quality one ok? its going to get shrunk down anyways right?

**Comment by KrushGames** [comment]
Black DNA
Gold DNA
Purple DNA
White DNA
hopefully these work

**Comment by HLXII** [comment]
This is a fairly old PR, so I'm not sure if it's still being planned.

However, we could also implement this using the new PokeLab mechanic in #1048.

[Bill's House](https://bulbapedia.bulbagarden.net/wiki/Sea_Cottage) in Kanto is where the Cell Separation System exists. The player could get research for that machine from there, which would then be used to make these forms available.

**Comment by Ultima1990** [comment]
Rezzing this ancient ass PR as prep for possibly/probably doing the same with Necrozma.

This now uses Krush's fancy graphics for the DNA items. It adds the DNA_ITEM_CHANCE constant for the drop rate. That constant is currently set to 60, but _should_ end up at 10 after being modified by DUNGEON_HELD_ITEM_MODIFIER and DUNGEON_BOSS_HELD_ITEM_MODIFIER. It should also be affected by the Item Magnet.

I've also moved Druddigon out of the Dragonspiral Tower boss pool to make farming these items ever so slightly less painful.

TODO:
Add an NPC to Icirrus City to explain the items and that the legendary dragon bosses will drop them.
Probably move Youngster Sarah to a different town.
Maybe move Dragonite out of the Dragonspiral Tower boss pool too.

**Comment by Ultima1990** [comment]
Sarah has moved. She got a new job. She's now Professor Juniper's Aide in Nuvema town. Still the roamer NPC.
The new Icirrus NPC is the Fan Club Chairman, since the Unova fan club is in Icirrus. No connection to the Vermillion guy. Included some Kyurem Reshiram Zekrom lore, but I think it still explains the mechanic well enough.

Didn't move Dragonite. Not gonna move Dragonite. Suffer!

This is done.

**Review by RedSparr0w — APPROVED** [review]
Changes look good, thanks for the PR! 👍

**Pull request merged**
