### PR TITLE
Diancie Quest changes

### PR DESCRIPTION
**Pull request by RedzepR**
## Description

- Removed the duoblade mon requirement for Diancie quest
- changed the wording of the quest steps around Blade Aegislash so they talk about the Steels' aegislash
- Remove the reward from the quest step and make it a gift NPC
- bugfix the fairy gem step of the diancie quest
- Added customDescription to GainGemsQuest
- bugfix Cipher Peon Naps dungeontrainer

## Motivation and Context

Was on  eugene171s list of "want to do but they're kinda small" (see screenshot) 

## How Has This Been Tested?

- Done the Diancie quest as a whole, tested the changed steps multiple times

## Screenshots (optional):

Ingame Screenshots
Eugenes request

## Types of changes

- Bug fix
- Changes to the Diancie Quest

### CODE REVIEW

**Comment by CypherX** [comment]
You used the same branch for these changes as you did for #4746, you should be using a different branch

**Comment by RegisCoaxans** [comment]
> Added customDescription to GainGemsQuest
Please do not, #4659 will take care of such need on a larger scale.

**Comment by Farboo171** [comment]
> > Added customDescription to GainGemsQuest
> 
> Please do not, #4659 will take care of such need on a larger scale.

That's my bad, I told then they should

**Comment by Farboo171** [comment]
> You used the same branch for these changes as you did for #4746, you should be using a different branch

Yeah that seems to be the case.

Might be easiest to close this PR and open with a new one, using a different branch.

**Comment by RedzepR** [comment]
> > You used the same branch for these changes as you did for #4746, you should be using a different branch
> 
> Yeah that seems to be the case.
> 
> Might be easiest to close this PR and open with a new one, using a different branch.

I will do that, sorry for the inconvenience

**Pull request closed without merging**
