### PR TITLE
[WIP-Draft] Party Slots

### PR DESCRIPTION
**Pull request by apple096**
Created this PR to keep track of the progress

- [ ] Party Slots
   * [ ] UI
     * [ ] Container
       * [ ] Party Images
       * [ ] Ability Tooltips
       * [ ] Cooldown timer (see Battle Items Container)
     * [ ] Pokemon List Modal to assign to Party Slot. May want to create base template for Pokemon lists since they're used in a couple of locations now (Pokedex, Hatchery, now Party Slots).
   * [ ] Update PartyPokemon to store location (e.g. In Party Slots).
- [ ] Abilities
   * [x] Base Class - Probably needs just name and description.
     * [ ] Passives - Will probably need to store all current passives and add references to them in correct locations. (egg, berry growth, etc).
     * [ ] Custom - Some abilities might have additional modals to open for options. Not sure of this one
   * [ ] Base Abilities
     * [ ] General passive multipliers (egg, harvest, money, etc)
     * [ ] General damage actives (damage, type, cooldown)
   * [ ] Custom Abilities
     * [ ] TBD
   * [ ] Pokemon Assignment - Assigning Pokemon abilities. Will need to update PokemonList.
 - [ ] Ability Capsules
   * [ ] Implement Item
   * [x] Add to Shop
   * [ ] Implement backend usage (probably will be used in new Pokemon List modal for Party Slots)

### CODE REVIEW

**Comment by anapple96** [comment]
So it begins I guess

**Comment by Ultima1990** [comment]
Exciting!

**Comment by HLXII** [comment]
Suggestion for breaking down the progress tasks

- [ ] Party Slots
   * [ ] UI
     * [ ] Container
       * [ ] Party Images
       * [ ] Ability Tooltips
       * [ ] Cooldown timer (see Battle Items Container)
     * [ ] Pokemon List Modal to assign to Party Slot. May want to create base template for Pokemon lists since they're used in a couple of locations now (Pokedex, Hatchery, now Party Slots).
   * [ ] Update PartyPokemon to store location (e.g. In Party Slots).
- [ ] Abilities
   * [ ] Base Class - Probably needs just name and description.
     * [ ] Passives - Will probably need to store all current passives and add references to them in correct locations. (egg, berry growth, etc).
     * [ ] Actives - Stores use method and cooldown
     * [ ] Custom - Some abilities might have additional modals to open for options. Not sure of this one
   * [ ] Base Abilities
     * [ ] General passive multipliers (egg, harvest, money, etc)
     * [ ] General active multipliers (egg for 10 mins, etc)
     * [ ] General damage actives (damage, type, cooldown)
   * [ ] Custom Abilities
     * [ ] TBD.
   * [ ] Pokemon Assignment - Assigning Pokemon abilities. Will need to update PokemonList.
 - [ ] Ability Capsules
   * [ ] Implement Item
   * [ ] Add to Shop
   * [ ] Implement backend usage (probably will be used in new Pokemon List modal for Party Slots)

I think that covers most of the general development. The rest is still in the design phase or will be part of Custom Abilities.

**Comment by anapple96** [comment]
Reopening

**Comment by apple096** [comment]
Update for anyone that checks the github channel : This is effectively over, I'm taking an indefinite break from this as a whole, so forget about it, think about new ways, and just know that this will never exist and you can't use it as a reason for not adding something from now on.
Bye.

**Pull request closed without merging**
