### PR TITLE
Images Packs

### PR DESCRIPTION
**Pull request by Sinonea**
The code is functionnal but must be optimized, the game is experiencing slowdowns ...
I know how to fix it but I'll do it later, I'm going to sleep.

## Types of changes

- Bug fix
- New feature
- UI improvement

### CODE REVIEW

**Comment by CypherX** [comment]
This is not something we want to implement, sorry

**Comment by Sinonea** [comment]
Hello !

@EatPant2nd helped me come to terms with the bitter decision you had to reject my 48 hours of work so easily. You didn't even give me time to express myself. The packs are optional and do not bother players in any way. It's a beneficial addition and like I said, if players don't want to use them, that's their right. But as a die-hard fan of the original games, I'm really in love with the images (especially the first two generations) and I made sure that if the image is not in the pack, the default one is used, I I did things according to the rules of the art so that this addition was accepted. Seeing him refuse hurt me a lot but hey, that's how it is, my passion is not recognized at its true value.

See you soon !

**Comment by osherwott** [comment]
I wanted to check this PR out but the page does not load 💀

**Comment by CypherX** [comment]
> Hello !
> 
> @EatPant2nd helped me come to terms with the bitter decision you had to reject my 48 hours of work so easily. You didn't even give me time to express myself. The packs are optional and do not bother players in any way. It's a beneficial addition and like I said, if players don't want to use them, that's their right. But as a die-hard fan of the original games, I'm really in love with the images (especially the first two generations) and I made sure that if the image is not in the pack, the default one is used, I I did things according to the rules of the art so that this addition was accepted. Seeing him refuse hurt me a lot but hey, that's how it is, my passion is not recognized at its true value.
> 
> See you soon !

Something like this falls into the category of _ask before doing_.

This would more than double the amount of images in the game. Having some sprites in one style while other sprites in a completely different style would be jarring and undoubtedly cause bug reports. It's just too much for a novelty feature.

I closed this quickly because it's a definite "no" and I didn't want you to continue spending time on something that was ultimately never going to be merged

**Comment by Sinonea** [comment]
Thank you for responding in such a gentlemanly manner! Thanks to your explanation, I was able to understand why and I completely understand it! It’s true that I should have asked before working on it! It's not wasted work, I keep the branch on my PC and it's true that there is a lot for a new feature. Thank you for opening my eyes! I remain available for other additions if necessary and I obviously remain available to improve Everstone and Encounters Modal. There are two open PRs for both features! Thanks to you !

**Pull request closed without merging**
