### PR TITLE
Kanto remap + Unova Overhaul

### PR DESCRIPTION
**Pull request by NiCeDiCe90**
Overhaul of Unova map.
Dock pushed sligly to the right, Bridge became a bit shorter

### CODE REVIEW

**Comment by NiCeDiCe90** [comment]
Added Kanto rework to the PR
Completely remapped from the scratch

**Comment by RedSparr0w** [comment]
For the Kanto map, could you make it so the routes are connected to each other/towns?

Current:
image

Connected:
image

**Comment by NiCeDiCe90** [comment]
Done. Looks better now. Thanks for the advice.

**Review by RedSparr0w — APPROVED** [review]
👍 Looks good, thanks for the PR

**Pull request merged**
