### PR TITLE
Fix several more broken rewards due to ID changes

### PR DESCRIPTION
**Pull request by CypherX**
Fixed:

- Urshifu (Rapid Strike) (was giving MissingNo.)
- Pinkan Pikachu (was giving Let's Go Pikachu)
- Pikachu (World Cap) (was giving Pikachu (Partner Cap))

Also switched other alt-form unlocks to be name-based rather than id-based.

We will most likely need an update function or something in `checkAndFix()` to unlock the proper Pokemon for players that may have completed these things while broken.

### CODE REVIEW

**Comment by RedSparr0w** [comment]
We're probably better off making a new method `gainPokemonByName` which takes the `PokemonNameType` so we will hopefully be able to avoid this in the future.
```js
    gainPokemonByName(name: PokemonNameType, shiny = false, suppressNotification = false, gender = -1) {
        const pokemon = pokemonMap[name];
        this.gainPokemonById(pokemon.id, shiny, suppressNotification, gender);
    }
```
This way it will validate it's a valid Pokémon name before reaching the main files.

**Comment by CypherX** [comment]
I'll update this PR to make use of `getPokemonByName` when #3674 gets merged.

**Comment by CypherX** [comment]
Updated to use newly added `getPokemonByName()` when awarding alternate forms.

**Review by Jaaslet — APPROVED** [review]
Looks good. Thanks for the PR

**Pull request merged**
