### PR TITLE
Notification settings are now grouped

### PR DESCRIPTION
**Pull request by Jaaslet**
Implements #1805
Problems, that might need to be fixed:

- [x] The HTML could be more compact/generated. I was having a hard time getting knockout to have a foreach inside a foreach
- [ ] The category titles changes place, when all categories are collapsed

### CODE REVIEW

**Comment by Jaaslet** [comment]
Currently, the category titles jumps around, when you collapse/uncollapse the categories. I don't know enough about CSS to be able to fix it. And i don't know if it's a big enough problem, that it needs to be fixed. But if it is, i need help

**Review by RedSparr0w — APPROVED** [review]
Looks great!

Thanks for the PR! 👍 

Would be great if we could do the same for sounds, is this something you'd want to work on?
If not I can do it.

**Comment by RedSparr0w** [comment]
Made some minor changes:
- Titles changed to buttons _(with small top margin to separate them)_
- Put each of the tables in a `div` so they shrink/grow correctly _(seems tables don't like how bootstrap grows/shrinks the collapsable elements)_

**Comment by Jaaslet** [comment]
> Would be great if we could do the same for sounds, is this something you'd want to work on?

I will do it, at some point

**Pull request merged**
