### PR TITLE
Add Rotom (discord)

### PR DESCRIPTION
**Pull request by RedSparr0w**
Saw someone talking about Discord Rotom a bit ago, figured I'd give it a go.
Probably as an event around May 13th (Discords Birthday)
Or on the Discord bot shop
Or both?

I think I prefer 5, not sure though..

Attempt | Standard | Shiny | Notes
:---: | :---: | :---: | :--
1 | Discord_Rotom | Discord_Rotom_Shiny | Initial attempt
2 | Discord_Rotom_2 | Discord_Rotom_2_Shiny | Very similar to 1, with slightly less border
3 | Discord_Rotom_3 | Discord_Rotom_3_Shiny | Moved the ping and typing things around
4 | Discord_Rotom_4 | Discord_Rotom_4_Shiny | Changed ping color to discords red
5 | Discord_Rotom_5 | Discord_Rotom_5_Shiny | Used the sparks from base rotom

[PXZ files for each version](https://github.com/pokeclicker/pokeclicker/files/8101596/Discord_Rotom.zip)
_from https://pixlr.com/e_

### CODE REVIEW

**Comment by Someonealive-QN** [comment]
All of these looks good but for me the best one is the 4 attempt every rotom form has only 2 "hands" not 4

**Comment by amative1** [comment]
I think #4 works the best, as it has the "correct" notification color and theming. #5 is a bit too "normal", if you get my meaning.

**Comment by jmcclain1299** [comment]
I like #4 as well, with the notification color

**Comment by RedSparr0w** [comment]
> every rotom form has only 2 "hands" not 4

Never realised this tbh, thanks!

**Comment by RedSparr0w** [comment]
Thanks for the feedback.
Added number 4, no obtain method currently.

**Pull request merged**
