### PR TITLE
A couple Alola fixes and changes

### PR DESCRIPTION
**Pull request by Ultima1990**
Changed Magearna's shiny sprite.
Changed Celesteela's sprites.
Changed Oricorio (baile)'s sprite.
Fixed a typo on the Royal Avenue NPC.
Added a NPC to explain Lycanroc Dusk.

### CODE REVIEW

**Comment by Ultima1990** [comment]
Made some changes to the Cap Pikachus.
Each Pikachu is now native to the region their cap originates from.
Decided to make Original Cap be the Johto cap, since Johto wouldn't have a Pikachu otherwise. Remember, Ash's costume didn't change from Kanto to Johto, Kanto cap = Johto cap = Original cap, and Kanto already has a bunch of Pikachus. So Original cap is now Johto cap.
Removed Parther Cap Pikachu from Pikachu Valley. To be used elsewhere.

**Review by RedSparr0w — APPROVED** [review]
👍 Thanks for the PR!

**Comment by Jaaslet** [comment]
> Each Pikachu is now native to the region their cap originates from.

This might affect the "get all pokemons"-achievement/challenge

**Comment by RedSparr0w** [comment]
> > Each Pikachu is now native to the region their cap originates from.
> 
> This might affect the "get all pokemons"-achievement/challenge

Very true, nice catch!

**Comment by Ultima1990** [comment]
Oh. Oh right. Oh no. That's not the intention, I just wanted to give players a full-power Pikachu in each region! Damn.

**Pull request merged**
