### PR TITLE
pokdexPokerusFilter -> pokedexPokerusFilter

### PR DESCRIPTION
**Pull request by LegitSi**
## Description
I added a character inside the hapax legomenon variable of pokdexPokerusFilter to be more consistent.

## Motivation and Context
In my search to fix another bug, I found this. That's it.

## How Has This Been Tested?
I opened inspect element in client with CTRL+SHIFT+I and found it at the very top.

## Types of changes

- [x] Bug fix
- [ ] New feature

### CODE REVIEW

**Comment by osherwott** [comment]
Thanks for using the form! Devs are very busy irl so it helps to be concise!

**Comment by CypherX** [comment]
As I mentioned on discord, the `pokdexPokerusFilter` value you are changing here is what's used to track the selected value for the pokedex pokerus filter in the save file. Changing this without an update function to also change the string in the save file causes the filter value to reset to 'All'.

**Comment by LegitSi** [comment]
I'll investigate how to do that tomorrow when I get back. Thanks for letting me know.

**Comment by Jaaslet** [comment]
I will close this, as it's a lot of work for a small refactor, and it's the PR is not finished

**Pull request closed without merging**
