### PR TITLE
Feature/more readable pokedex

### PR DESCRIPTION
**Pull request by lenormandSeb**
Based on this issue : https://github.com/pokeclicker/pokeclicker/issues/2643

I remove unobtainable form of some pokémon like Arceus on the screenshot, and the big "show alternate form" button.

I've test with an 0.9.5 and 0.9.8 save without problems, I hope that you will appreciate it.

PS: my english is still bad, you can blame google translate :smile: 

(some screen)

Capture d’écran du 2022-07-14 23-49-10
Capture d’écran du 2022-07-14 23-49-31
Capture d’écran du 2022-07-14 23-50-05
Capture d’écran du 2022-07-14 23-50-25

### CODE REVIEW

**Comment by NiCeDiCe90** [comment]
I don't really see the improvement of your Dex rework. :/

You see less Pokémon in the Overview (only 5) and the information being spread over the entire width makes is less readable actually. The current dex is more compact and I can see the same information. But way more pokemon at once.

The Labels for typing work pretty well for people who are not that familar with the typings but I think the background colors in the current dex look way better.

I can see the idea behind removing the alternate forms to make it less cluttered with walls of pikachu/unown/vivillon or a bazillion of Alcremie in the future. But since they are all individual Pokémon in your team, they may also deserve their own dex entry.

Not having them also gives wrong information about the alternate forms too.
Bulbasaur (Rose) for example is not grass/poison. It's a grass/fairy type. I assume you see that if you click on the form but as a player I would assume here that they are all the same type.

If you have a lot of forms you also have to scroll a lot to see all the statistics and stuff. Takes some time to get information about your Unown (Z) in your Dex. In the current dex you can find it way faster and you have the popup that is consistently the same size for all Pokémon.

**Comment by Jaaslet** [comment]
The dev team agrees with @NiCeDiCe90.
I will close this PR. Sorry. But thanks for trying.

**Comment by lenormandSeb** [comment]
Don't worry, I understand :smile:  there's a lot of change and my approach was going in the wrong direction.

I take note of the point of view of Nice and the majority of the players, by extension that of the devs too.

I will continue to issue smaller and more digestible suggestions.

And thank you for your feedback. :+1:

**Comment by Jaaslet** [comment]
Bigger PRs are fine. Just make sure they are accepted, before you start :)

**Pull request closed without merging**
