### PR TITLE
Fix of LevelType

### LINKED ISSUE #1499: [BUG] Some pokemon have incorrect levelType
**Info**
Several pokemon in PokemonList.ts have a levelType of `4` instead of the expected `LevelType.something`. All cases appear like they should be `LevelType.fast`, but `4` is actually the "slow" level type.

**Steps to Reproduce:**

1. Go to PokemonList.ts
2. Ctrl+f `'leveltype': 4`

**Expected Behavior:**
`levelType` key should be `LevelType.something`, probably `LevelType.fast` in all cases, but double check with bulbapedia.

### PR DESCRIPTION
**Pull request by jk13pclick**
Changed all 4s to LevelType.fast as per Bulbapedia, fixes #1499

### CODE REVIEW

**Comment by jk13pclick** [comment]
Closing because duplicate of #1501

**Comment by jk13pclick** [comment]
Reopening :)

**Comment by NiCeDiCe90** [comment]
This is comedy that can't be scripted. 👍

**Review by RedSparr0w — APPROVED** [review]
Thanks for the PR!, Looks good.

**Pull request merged**
