### PR TITLE
Startmenu: Moved up events

### PR DESCRIPTION
**Pull request by Jaaslet**
## Description

The Events button is moved up, as it now does something, when you own the event calendar. I moved it right above all the items, that does not open something that affects the game.

## Motivation and Context

Makes the start menu easier to use

## How Has This Been Tested?

I opened the game and saw the achievement button was gone, and the event button was moved up

## Screenshots (optional):

image

## Types of changes

- UI improvement

### CODE REVIEW

**Comment by DraKay** [comment]
Special files have less than 110 pokes, example pant

**Comment by CypherX** [comment]
The achievements module is locked until the player has captured 110 unique pokemon, so removing it from the start menu will prevent players doing certain types of challenge runs (monotypes mainly) from accessing achievements completely.

Perhaps we can hide the start menu item after the module is unlocked, or lower the amount of unique pokemon required (or remove that requirement altogether).

**Comment by Qwertypop04** [comment]
Perhaps instead of having it be unlocked by number of Pokémon, have it be unlocked by progress? (Like gem case, for example)

**Comment by Jaaslet** [comment]
Oh, then it makes sense that it's there. Yeah, unlock it earlier/in some other way, might make sense. I will remove it from this PR, as it will require some discussion

**Review by RegisCoaxans — APPROVED** [review]

**Review by RedSparr0w — APPROVED** [review]
Sounds good, thanks for the PR! 👍

**Pull request merged**
