### PR TITLE
Decrease dungeon size for every 10, 100, 1000 etc defeats to a minimum of 5x5

### PR DESCRIPTION
**Pull request by RedSparr0w**
Decrease the dungeon size for every 100 clears (to a minimum of 3x3).
Show all chest when (floored) dungeon size / 3 chest have been opened
Show entire dungeon when (ceiling) dungeon size / 2 chest have been opened

### CODE REVIEW

**Comment by scolpitts536** [comment]
Tbh I'm not a fan of 3x3 dungeons, one kanto becomes a cake walk easily. I feel like 5x5 minimal should clear any dungeon with ease but not be so easy babies can do it.

**Comment by anapple96** [comment]
Same, 3x3 too small, 5x5 min is probably best

**Comment by RedSparr0w** [comment]
There's currently a vote in the Discord for sizes/method of size reduction.

**Comment by RedSparr0w** [comment]
As per the current poll in Discord have updated to be minimum size of `5 x 5`, and decrease in size once cleared 10, 100, 1000 etc times.

**Comment by GarrikFel** [comment]
It makes me sad that the log_10 option won the poll.  I wonder how many of those people are actually doing dungeons.  When we get to Galar I was hoping to not spend most of my dungeon time in a 10x10 dungeon...

**Comment by Claygame** [comment]
reducing size on 10 & 100 clears is ok but next reduction needing 1000 clear is not useful. This feature is so that people can reach 1000 clear in later region dungeons easily where they are so big that reduction of size just 2 times wont really make it any easier/faster to get the 1000 clears.

**Comment by GarrikFel** [comment]
It's still technically useful if you're shiny hunting.  There's a good chance that you won't have all the shinies after 1,000 clears, and in gen4+ your egg hatching shinies are still probably lagging behind so that it makes sense to do those dungeons more than 1,000 times.  I agree that the log_10 option isn't super useful, but it is still kind of useful.

**Pull request merged**
