### PR TITLE
Fix console error jumping from dungeon to town

### PR DESCRIPTION
**Pull request by LuqDragon**
just a little thing i saw when playing on anapple unova map
console

### CODE REVIEW

**Comment by RedSparr0w** [comment]
I haven't seen this problem on the main game, there's likely a problem somewhere with the Unova stuff which needs to be fixed.

We also can't use `?.` in our javascript (the data-bind stuff isn't parsed by typescript), as the support just isn't quite fully there yet.

**Comment by LuqDragon** [comment]
i tested on my desktop version and have the same issue, you need to go to a town that dont have a dungeon access

**Comment by RedSparr0w** [comment]
Ah yeah, that is strange, it seems to be the left overs of the old dungeon/town, even though the town should have changed already 🤔
This line _should_ already be handling it, not sure why it's not being picked up from there
image

**Comment by LuqDragon** [comment]
Maybe it update faster than the knockout collapse/remove

**Review by RedSparr0w — APPROVED** [review]
Looks good, thanks for the PR!

**Pull request merged**
