### PR TITLE
Added female Eevee and fixed Let's Go ratios to gender of sprites

### PR DESCRIPTION
**Pull request by osherwott**
* Added female Eevee sprite that was canonized as a general gender difference after Let's Go. As per official sources, it is modeled to resemble a heart from the side.
* Fixed gender ratio of current Let's Go Pikachu to female, and Eevee to male, as to not meddle with original sprites yet keep the gender consistent and perhaps make them a bit more unique.
* Fixed Detective Pikachu's gender to male, as per canon.

No pokeclicker-original sprites were changed, but below is a list of pokemon forms without gender differences, excluding the Let's Go sprites, whose base forms do have a difference:
- Pinkan Pikachu
- Flying Pikachu
- Surfing Pikachu
- Gengar Pikachu (I recommend making the female's costume a Clefable, it'd be _so_ cute)
- Detective Raichu
- Valencian Vileplume
- Pinkan Vileplume

### CODE REVIEW

**Comment by DraKay** [comment]
Pinkan Pikachu is Ash Pikachu after eating a pinkan berry in an anime episode so is only male
For surfing and flying Pikachu are based in TCG cards that only shows them as male, so also cannon male
Gengar Pikachu is based upon a softy toys collection and I don't remember it having clefable so it wouldn't make sense
Detective raichu is cannon only male
For Valencian vileplume artist and me (made pinkan female pr) decided not make a female sprite as changed part in female isn't keeped in valencian
And unless I forget to add, pinkan vileplume already have female sprite

**Comment by DraKay** [comment]
I checked my pr and pinkan vileplume is in code already also I don't see the logic of gengar Pikachu.... Gengar is a pokemon that have both genres also at 50% rate, so why female ones can't have a spooky costume and need to have a "cute" (using your own words) one? In my personal opinion that's giving a very ugly message you are telling girls  need to be cute and can decide to be spooky... I want to think you didn't want to send that message and insult 50% of population with it...

**Comment by osherwott** [comment]
Good to hear, I will fix Pinkan Pikachu and Gengar Pikachu's gender to male as well.
Surfing and Flying Pikachu have been distributed as event pokemon in many iterations, but it they are modeled after specific ones then say the word and I'll fix their gender too.
Detective Raichu is in no canon and only exists in Pokemon Go, where the female form exists in the code yet hasn't been available, hence me leaving it alone.
And you are right about Vileplume, I must have not noticed it because I was double-checking all the genders!

As for your other comment, having Pikachu wear a Clefable costume was simply a recommendation and has nothing to do with its gender, but more with the fan-theories of Gengar and Clefable being connected. I thought it would be cute to have them match :) Also I find Pikachu's Gengar costume cute too! I didn't know you meant for it to be spooky, sorry!

**Comment by Farboo171** [comment]
You should probably run this by the devs in the discord before trying to make changes. Saves a lot of work that could get thrown out.

**Comment by osherwott** [comment]
@Farboo171 I don't mind making a quick PR for a couple of pixels. Rest assured that I am aware bigger projects benefit from collaboration on discord, and will make sure to properly contact the devs and tag more expansive ideas as suggestions in Issues!

**Comment by Jaaslet** [comment]
Where is the Eevee taken from? The smogon project already has a female version of Eevee, and this does not look like that one.
We would prefer if you used that one. But if not, at least we need you to add credits for it.
But the rest looks good

**Comment by jk13pclick** [comment]
> I didn't notice the smogon version because I was mistakenly looking at their gen 8 spritesheet instead of their gen 7 one! The sprite above was made by me in an effort to remain faithful to official sources of the heart-shaped pattern when viewable from the side. It is not so much of an error as their Marine and Ocean Vivillon (3d models of Eevee and its anime appearance don't remain consistent with the side heart-shape either), so I'd be glad to use their female Eevee sprite if you find it more preferable.

We have decided that we want the Smogon one. Thank you!

**Comment by osherwott** [comment]
Updated with Smogon Eevee sprites!

**Review by Jaaslet — APPROVED** [review]
Looks good. Thanks for the PR

**Pull request merged**
