### PR TITLE
Magikarp jump forms

### PR DESCRIPTION
**Pull request by Jaaslet**
This PR just adds all the mon data and images.
Some of the translations: https://github.com/pokeclicker/pokeclicker-translations/pull/36 (not sure if i will finish it)

### CODE REVIEW

**Comment by Aegyo** [comment]
I'll take care of the translations.

I assume the pokedex order is official in some way?

**Comment by osherwott** [comment]
The dex order is correct. Every major language wiki shows their number along with their name, so it should be consistent across all references. Good luck! 👍 

Also non-shiny sprite 129.27 accidentally has white whiskers instead of yellow, and 129.03 should be Orange, White, Black instead of Orange, White, Brown. Other than that, it's great!
image

**Comment by Jaaslet** [comment]
Stuff is fixed. I even fixed the translations: https://github.com/pokeclicker/pokeclicker-translations/pull/41

**Comment by Aegyo** [comment]
It looks like you replaced the sprite for .26 (black forehead) with the whisker-corrected .27 image (black mask)

**Comment by Jaaslet** [comment]
Fixed!

**Review by Aegyo — APPROVED** [review]

**Pull request merged**
