### PR TITLE
Fixup `TownList.ts` pokémon alternate forms image url

### PR DESCRIPTION
**Pull request by Farigh**
The quest displays as:
image

Instead of: 
image

### CODE REVIEW

**Comment by Farigh** [comment]
Repushed, I fixed a typo as well

**Comment by Farigh** [comment]
Fixed some more images.

[This commit](https://github.com/pokeclicker/pokeclicker/commit/e5df47bfca232404829912dff5d5ac80434ad58e) changed the image names and might have broken other ones.

I did a quick check on all images of the TownList.ts file.

**Comment by Farigh** [comment]
It should be the only cases of hard-coded images : 
image
(this one is not a pokémon, and [was not renamed anyway](https://github.com/pokeclicker/pokeclicker/blob/develop/src/assets/images/dynamic-background/cloud/08.1.png))

image

**Review by Jaaslet — APPROVED** [review]
Looks good. Thanks for the PR

**Pull request merged**
