### PR TITLE
Encounters modal improvements

### PR DESCRIPTION
**Pull request by Sinonea**
## Description

Improved the route part of my modal encounters. Separation of the 'Pokémon' and 'Roamers' groups (the groups can be collapsed). Both lists are sorted by pokemon ID. Added different icons to give more information about the Pokémon in question:
- Roaming (no Event)
- Event (no Roaming)
- Event Roaming
- Fishing (Pokémon who needs the Super Rod to be catch, if the route has no land pokémons, this icon is not displayed)
- Weather (Galar)
- Day of Week (Alola)
- ~~Special (the others, aka Quest, need himself to be catch, etc...)~~ -> This one is removed due to the desire of developers

## Motivation and Context

The first PR (#5343) was to introduce the Encounter Modal, not knowing if the modal was going to be introduced to the game or not. So I did the bare minimum and it was more of a beta version of my modal. Now that modal has been introduced to the game, I have had various bug feedbacks and various ideas to improve the view of the route. The bugs were fixed in a previous PR (#5426) and here I am with an improved version where I added lots of little details to make it look nice.

For the images used, I drew from the game's image gallery and I tried to be consistent with what I wanted to convey as information, the icons seem to speak for themselves but the most interesting according to me are those from "Day of Week" and "Weather" where I took the quest items from "Ho-Oh" and "Lugia" respectively. Ho-Oh being the master of the day and Lugia being the master of weather, it seemed like a good correlation to me given the lore of the two Pokémon. Don't hesitate to change the images if it doesn't suit you! I did it by feeling without any real convictions.

The next step could be to improve the dungeon part and once the PR here has been accepted, work on a Pokémon view dungeon in the same style as the route part, this will be a modal in addition to what is already existing . On the beta, I didn't worry about it since it existed and as I said, I wasn't sure if the modal would be accepted.

## How Has This Been Tested?

I have been on the different routes to see the icons appear. See the screenshots.

## Screenshots (optional):

image
image
image
image
image
image
image
image
image
image
image
image
image
image
image

## Types of changes

- UI improvement : Encounter Modal (Route part)

### CODE REVIEW

**Comment by CypherX** [comment]
Apologies it's taken so long to get to this. Looks good for the most part, but there are a few small changes we want:

- Please fix the conflict
- Change "Super Rod Pokemon" to "Fishing Pokemon"
- Remove the "Special Pokemon" icon and tooltip, just have them appear as regular encounters

Let us know if you're unable to get to this, thanks

**Comment by Sinonea** [comment]
Hey ! No problem for the time !

I'm able to do all you want !

I'll do this evening.

Thanks !

**Comment by Sinonea** [comment]
The @RegisCoaxans modifications are included in the improvements as the image prove :
image
The modification for the fishing pokémon :
image
The removing of the icon "Special Pokémon" (here on Malosse)
image

**Comment by Sinonea** [comment]
I've no idea how to resolve the conflit but I've included the modifications by REgis to my code. I suppose it's okay.

**Comment by Sinonea** [comment]
So ! I've done my work, I let you with the gitub issues. I'm not familiar with github !

Thanks

**Comment by Sinonea** [comment]
Hey @CypherX !

I'm viewing your changes ! Good work !

I've seen you've modified the code to remove the call of hasInformation function with the keyword "with". It's possible to remove complety the function with replacing 

by 


and remove the hasInformation function ?

Thanks !

Aenonis

**Comment by CypherX** [comment]
Yeah that should work, thanks

I'm gonna merge this now, just one note: in the future (and if you ever want to refactor this) please use proper typescript typings

**Comment by Sinonea** [comment]
Thanks for your merge !

I've a question : what is the "proper typescript typings" ?

I've done mistakes ?

Thanks fully !

Aenonis

**Pull request merged**
