### PR TITLE
chore(circular): moves notification constants into separate file

### PR DESCRIPTION
**Pull request by SpenserJ**
This is needed in order to begin reducing the number of circular dependencies within the code, and support the eventual move to proper TypeScript dependencies and type checking. An example of a circular dependency for `GameConstants.ts` (there are ~136) is `GameConstants.ts > utilities/Sound.ts > settings/Settings.ts > GameConstants.ts`, and the only reason these haven't cause a noticeable issue is because everything is pushed into `window` and most of the code isn't set up to import the types that it uses.

Despite being such a large number of lines changed, the changes can be summarized as:
* Move the three `Notification*` enums into a `NotificationConstants.ts` file
* Split most of the `Notifier.notify` calls onto multiple lines to improve readability (some lines were ~300 characters long)
* Replace `GameConstants.Notification` with `NotificationConstants.Notification` (case by case, instead of using replace all, just to double check everything)

### CODE REVIEW

**Comment by RedSparr0w** [comment]
Thanks for the change, this definitely makes more sense.

Though do you think instead of having the `NotificationConstants` these could just be a static property of `Notifier`?

```js
class Notifier {
    static setting = [];
    static sound = [];
    static type = [];
}
```

**Comment by SpenserJ** [comment]
Potentially, however the driving force behind a few of these changes (there are quite a few coming) is reducing the circular dependencies. As long as I can set it up that Notifier doesn't import other code (or at least something that eventually imports Notifier), it shouldn't be a problem. Sound and Setting is a bit of a challenge with how it is currently written, since they have a circular dependency between them, so it might be better as a future improvement, but I'll take a quick look when I have some time if it is a blocker

**Comment by RedSparr0w** [comment]
> there are quite a few coming

It might be worth us merging the [Unova branch](https://github.com/pokeclicker/pokeclicker/tree/unova) sooner than later then, otherwise these are going to create a bunch of conflicts there.

**Comment by SpenserJ** [comment]
Yeah, I'm sure I'll be causing many conflicts as I move things around. Is there a list of outstanding tasks for that branch? I would be happy to help finish it up before I cause more chaos

**Comment by RedSparr0w** [comment]
The PR is #749, there's still quite a lot to do before Unova is playable,

We can merge the PR into the develop branch once we have the town images though,
_(it won't make Unova playable, but will allow us to avoid merge conflicts)_
Or we can just disable trying to preload the images for unreleased regions (which is probably a good idea anyway).

**Comment by SpenserJ** [comment]
Fantastic. I'm a fan of merging things in more regularly and having it disabled or hidden behind feature flags. Do you have any interest in using [project boards](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/creating-a-project-board) to track some of the work at a higher level (probably the top level tasks from the PR), or would you prefer to keep it in code?

**Comment by SpenserJ** [comment]
@RedSparr0w I've updated this to target the `unova` branch now

**Review by RedSparr0w — APPROVED** [review]
Changes look good!

Thanks for the PR 👍

**Pull request merged**
