### PR TITLE
Key Item visual fixes

### PR DESCRIPTION
**Pull request by DataCrusade**
Replaced the Pokerus key item image with a sprite to match the rest of the key items.

Fixed some errors with Key items. The image files are more consistent in size so they appear at a consistent resolution, and fixed a few errors in the name and descriptions

### CODE REVIEW

**Comment by Jaaslet** [comment]
I need to know what the Pokerus key item is. I am not sure we want to change it, but it's relevant for us to know what it is, and where you got it from. We at least need to know if it's an icon we want to use for something else, some day.

**Comment by Ultima1990** [comment]
That PokeRus replacement... That's quite something. It's certainly a higher quality sprite, but also it's not just a visual upgrade. It's a completely different thing. A bottle of... whatever.

**Comment by DataCrusade** [comment]
> I need to know what the Pokerus key item is. I am not sure we want to change it, but it's relevant for us to know what it is, and where you got it from. We at least need to know if it's an icon we want to use for something else, some day.

Uh, it was added whenever EVs were added I think, this is what it currently looks like on v0.9.7
image

**Comment by Ultima1990** [comment]
To further expand on the PokeRus thing. I would be fine with making a better sprite for the key item (and also a rename, PokeRus Virus is a case of RAS syndrome). But that bottle looks like it'd be something like a potion. Something you'd drink from.

If someone wants to make a custom sprite for us I'd welcome it. I imagine it'd be something closer to a test tube.
image
Or one of these things:
image
(even though these are for bacteria, not viruses).

**Comment by DataCrusade** [comment]
> That PokeRus replacement... That's quite something. It's certainly a higher quality sprite, but also it's not just a visual upgrade. It's a completely different thing. A bottle of... whatever.

It's a vial with pokerus in it

**Comment by Jaaslet** [comment]
> Uh, it was added whenever EVs were added I think, this is what it currently looks like on v0.9.7

I was talking about the new image... :) Is the sprite taken from an item in a pokemon game? Did you find it on the internet?

**Comment by DataCrusade** [comment]
> I need to know what the Pokerus key item is. I am not sure we want to change it, but it's relevant for us to know what it is, and where you got it from. We at least need to know if it's an icon we want to use for something else, some day.

oh wait I think you meant where the image is from, I made it myself from scratch in like 10 minutes (just used some colors from the DNA Splicers key item)

**Comment by Jaaslet** [comment]
Images either need to be from the main pokemon game, or added to Credits.ts. Then we can always figure out where the images come from, and if we have rights to use them

**Comment by DataCrusade** [comment]
Added credits, and I think a test tube would be too small but I can mess with it some more.

**Comment by DataCrusade** [comment]
image
the bottom should read more as a test tube here

**Comment by Ultima1990** [comment]
I do prefer the test tube, yes. Maybe a bit less liquid and one of them stickers you put on the bottle?

**Comment by DataCrusade** [comment]
> I do prefer the test tube, yes. Maybe a bit less liquid and one of them stickers you put on the bottle?

image

**Comment by DataCrusade** [comment]
Updated sprite to test tube

**Review by Jaaslet — APPROVED** [review]
Looks good. Thanks for the PR

**Pull request merged**
