### PR TITLE
Adjusted Sonia's name

### PR DESCRIPTION
**Pull request by DataCrusade**
Unless I'm missing something, there wasn't any need to include Sonia's last name and it  just confused me /shrug

### CODE REVIEW

**Comment by Ultima1990** [comment]
Shouldn't it be Professor [Last name] then? It's the same with Oak. Named Samuel Oak, known as Professor Oak.

**Comment by DataCrusade** [comment]
> Shouldn't it be Professor [Last name] then? It's the same with Oak. Named Samuel Oak, known as Professor Oak.

Her grandmother is Professor Magnolia, so she can't also be Professor Magnolia

**Comment by Qwertypop04** [comment]
> Shouldn't it be Professor [Last name] then? It's the same with Oak. Named Samuel Oak, known as Professor Oak.

That would be her grandmother. There are two Professors Magnolia

**Comment by Qwertypop04** [comment]
> Professor Magnolia Jr.?

She is referred to as Professor Sonia in game iirc. So that makes most sense even if Professor Magnolia didn't exist.

**Comment by Ultima1990** [comment]
Ah. If it's Professor Sonia in-game then that's fine.

**Review by Jaaslet — APPROVED** [review]
Looks good. Thanks for the PR

**Pull request merged**
