### PR TITLE
Caught Alternate forms replace Base Uncaught forms

### PR DESCRIPTION
**Pull request by osherwott**
This should work. Please give feedback if there are any issues.

Currently only works if a pokemon has less than 99 forms.

### CODE REVIEW

**Review by Jaaslet — CHANGES_REQUESTED** [review]
I am not sure what this PR is trying to solve? At least i can't see any changes.
And instead of looping over the IDs, you can just look at the pokemonList what mons there are (filter by floor(id))

**Comment by osherwott** [comment]
Apologies! I have a bad habit of rushing without properly explaining.
This PR attempts to solve #3253. The loop checks if there are any caught alternate forms of that pokemon species id. From what I can see, filtering by floor(id) only works if it is based on the id of the alternate form, which is already checked for in the earlier if statement. I am trying to make it so that, given a base pokemon's id, that same base form can be checked for and returned false. If you have an idea on how to use floor(id) to make this check please feel free to elaborate!

Below are examples of the code in action:
uncaught
rubycream
ruby and vanilla

**Comment by Jaaslet** [comment]
Closes #3253 
(Just linking stuff while i remember. Will look at it tomorrow)

**Review by Jaaslet — APPROVED** [review]
I cleaned up the code.
Looks good. Thanks for the PR

**Pull request merged**
