### PR TITLE
Diancie Quest changes

### PR DESCRIPTION
**Pull request by RedzepR**
## Description

- Removed the duoblade mon requirement for Diancie quest
- changed the wording of the quest steps around Blade Aegislash so they talk about the Steels' aegislash
- Remove the reward from the quest step and make it a gift NPC
- bugfix the fairy gem step of the diancie quest
- bugfix Cipher Peon Naps dungeontrainer

## Motivation and Context

Was on eugene171s list of "want to do but they're kinda small" (see screenshot)

## How Has This Been Tested?

Done the Diancie quest as a whole, tested the changed steps multiple times

## Screenshots (optional):

ingame
request

## Types of changes

- Bug fix
- Changes to the Diancie quest

### CODE REVIEW

**Comment by Farboo171** [comment]
Two comments:
1. The gift NPC should read "Argus and Millis Steels' Aegislash"
2. The code cleanup part of this PR is significant and should be broken out into a separate PR for its own evaluation.

**Comment by RedzepR** [comment]
The code cleanup is just me removing my comments that i left - no other code was changed. Is it still relevant to do a second PR for that?

**Comment by RedzepR** [comment]
> > The code cleanup is just me removing my comments that i left - no other code was changed. Is it still relevant to do a second PR for that?
> 
> Check out the Files Changed on this PR, QuestLineHelper and TownList have many many small changes. Were these intentional?

I see what you mean now. No these were not intentional and were probably done by the IDE

**Comment by Farboo171** [comment]
I don't think we ought to merge unintended changes then. Do you want me to clean it up, or will you?

**Review by Farboo171 — APPROVED** [review]
Looks good now! Removed the Doublade requirement again (Looked like it got lost in the merge shuffle).

Thanks for the PR!

**Pull request merged**
