### PR TITLE
Make the shop 'Max' button able to work beyond 1 million items

### PR DESCRIPTION
**Pull request by Aegyo**
Uses a binary search to find the max amount of items
Seems to take around 53 iterations in most cases

Tried the make the binary search part of the code general so that it can be used in other parts of the game.

When you try testing if it is really giving the max, make sure you are not on a route collecting money  :sweat_smile:

### CODE REVIEW

**Comment by unclebanks** [comment]
What will happen if you're on a route collecting money?

**Comment by PixLSteam** [comment]
> What will happen if you're on a route collecting money?

Well, you might be able to afford more than before 😅 The 53 iterations make sense to me, because `Math.log(Number.MAX_SAFE_INTEGER) / Math.log(2)` equals 53.

**Comment by Aegyo** [comment]
The "max" number won't update with your new money total, and you will then be able to add 1 to the amount the button suggested and find you can buy more... making you think the code is broken (as I did when testing it myself)

**Review by RedSparr0w — APPROVED** [review]
👍 Looks good, Thanks for the PR!

**Pull request merged**
