### PR TITLE
Loot Rebalance (Round 1)

### PR DESCRIPTION
**Pull request by jk13pclick**
Something weird happened, this is an identical PR without the weirdness.

### Repost

Needs a crew test, big nerf to most loot.

Other Stuff:

More aggressive loot curve (10^weight -> 15^weight)
Better type checks
Nerf for returning to earlier regions to farm loot
Requirements, some new loot, more berries, more mimics

### CODE REVIEW

**Comment by NiCeDiCe90** [comment]
Can you tell me how much the weight affects the probabilities? Maybe for one sample dungeon at 1, 100, 1000 clears?
I guess lower weight loot becomes even less common?

I didn't check every dungeon but in generel I think it's a good rebalance so far.
But maybe we should add some different unlock requirements for some of the Items.

For example the metal coat should be unlocked after having steelix or Scizor in the dex.
So you cant just get the items for free before you at least bought one in Johto with QP before. 

For medium restore maybe add the requirement to have at least mined 100 layers in the underground. For large restore it should be like 1k items mined or something like that.
We are talking about a 400.000$ item here so it should not be that easy to get before you had some progress in the underground.

About the mimics: I hate them and they are very unfun to encounter for me. xD
But I think adding rock smash encounters is indeed a valid addition. I'm fine with it...

Now for the berries.
You added some hard requirements to get very rare gen5 berries. Not many people would do 1500 runs just to have a low chance for a ganlon. It might be faster to just mutate them. But I would still prefer the additional requirement to have the ganlon berry unlocked before you can farm it in a dungeon.
They have no use now but that might change at some point in the future so it should be unlocked by farm progress first before you can get it from other sources.
Same goes for all other berries. I'm fine with a passho farm later in the game but you should have unlocked the "normal" way before. Just getting them for free after some dungeon runs devalues the farming too much imo

Last but not least:
We can get some pretty expensive Items in dungeons but also like 1 Ultraball? 
In Gen3+ that's not really worth anything anymore.
So maybe we should add higher amount to them in later game chests.
Like 3x Ultraball in Hoenn, 5x in Sinnoh, 7x in Unova, 10x in Kalos.
It's still worthless because you easy buy them in 10k+ bulks in Kalos but still better than just getting 1 all the time.

**Comment by jk13pclick** [comment]
Okay, I thought about the whole "lock items until you get one the normal way" idea and I think I agree. However, I want to expand that idea to held items as well - getting a first Lum from Celebi has always been weird to me. I want to look into making a separate PR that accomplishes both of these things: restrict loot from dropping if you haven't unlocked the item yet, and restrict held items from dropping if you haven't unlocked the item yet.

**Comment by gilbertorussi** [comment]
Viridian Forest rework, for context

Before
| Loot         | Weight | Min clears | 0     | 10   | 100  | 500   | 0      | 10     | 100    | 500    |
| ------------ | ------ | ---------- | ----- | ---- | ---- | ----- | ------ | ------ | ------ | ------ |
| Lucky\_egg   | 4      | 0          | 10001 | 1001 | 101  | 21    | 47.36% | 47.28% | 46.12% | 40.38% |
| xAttack      | 4      | 0          | 10001 | 1001 | 101  | 21    | 47.36% | 47.28% | 46.12% | 40.38% |
| Pokeball     | 3      | 0          | 1001  | 101  | 11   | 4     | 4.74%  | 4.77%  | 5.02%  | 7.69%  |
| SmallRestore | 2      | 0          | 101   | 11   | 3    | 3     | 0.48%  | 0.52%  | 1.37%  | 5.77%  |
| Grass egg    | 1      | 0          | 11    | 2    | 2    | 2     | 0.05%  | 0.09%  | 0.91%  | 3.85%  |
| Leaf Stone   | 0      | 0          | 2     | 1.1  | 1.01 | 1.002 | 0.01%  | 0.05%  | 0.46%  | 1.93%  |

After
| Loot         | Weight | Min clears | 0           | 10          | 100         | 500         | 0      | 10     | 100    | 500    |
| ------------ | ------ | ---------- | ----------- | ----------- | ----------- | ----------- | ------ | ------ | ------ | ------ |
| xAttack      | 4      | 0          | 50626       | 5063.5      | 507.25      | 102.25      | 75.35% | 75.31% | 74.65% | 71.56% |
| Pecha        | 3.5    | 0          | 13072.31879 | 1308.131879 | 131.7131879 | 27.14263759 | 19.46% | 19.46% | 19.38% | 18.99% |
| Pokeball     | 3      | 0          | 3376        | 338.5       | 34.75       | 7.75        | 5.02%  | 5.03%  | 5.11%  | 5.42%  |
| SmallRestore | 1.75   | 0          | 115.3298683 | 12.43298683 | 2.75        | 2.75        | 0.17%  | 0.18%  | 0.40%  | 1.92%  |
| Grass egg    | 1      | 100        | 0           | 0           | 2           | 2           | 0.00%  | 0.00%  | 0.29%  | 1.40%  |
| Leaf Stone   | 0      | 0          | 2           | 1.1         | 1.01        | 1.002       | 0.00%  | 0.02%  | 0.15%  | 0.70%  |

**Review by RedSparr0w — APPROVED** [review]
Looks good, thanks for the PR! 👍

**Pull request merged**
