### PR TITLE
Hoenn Dungeon Trainers

### PR DESCRIPTION
**Pull request by Ultima1990**
Yea I'm doing each region in a separate PR. Dunno if that's smart. Lemme know.

### CODE REVIEW

**Comment by Ultima1990** [comment]
That's enough for today. New sprites added so far:

Camper
Dragon Tamer
Magma Admin
Magma Leader
Old Couple
Team Aqua Grunt (male+female)
Team Magma Grun (male+female)
Triathlete (malecycling+femalecycling+malerunning+femalerunning+maleswimming+femaleswimming)

**Comment by Ultima1990** [comment]
That was probably the final dungeon, unless I go back and add the Mossdeep Space Center.

Final new sprite list:

Aqua Admin (matt+shelly)
Aqua Leader
Camper
Dragon Tamer
Hex Maniac
Magma Admin
Magma Leader
Old Couple
PKMN Trainer (wally)
Team Aqua Grunt (male+female)
Team Magma Grunt (Male+female)
Triathlete (femalecycling+femalerunning+femaleswimming+malecycling+malerunnig+maleswimming)
Young Couple

TODO:
Backgrounds for new dungeons
Update.ts

MAYBE TODO:
Add Mossdeep Space Center
Move Aqua Hideout out of Lilycove and put it on the map

**Comment by Qwertypop4** [comment]
Thought I should mention that if you want to put Steven in, he actually is in a dungeon: Meteor Falls in Emerald.

**Review by RedSparr0w — CHANGES_REQUESTED** [review]
Looks good, just a couple more changes needed:
The Aqua hideout needs to be added to the map image and svg.
The Update.ts needs the dungeon indexes added.

**Review by RedSparr0w — APPROVED** [review]
👍 Looks good, Update.ts working well.
Thanks for the PR!

**Pull request merged**
