### PR TITLE
Implements #997 - Updated click attack formula

### PR DESCRIPTION
**Pull request by benanderson1**
Updated click attack formula as per the approved suggestion #997 

First PR, starting off nice and easy. 

Feel free to comment and add suggestions.

# Updated Click Formula

```
   Click Attack Formula:
            Damage = Caught ^ (4/3) + ((Attack * Caught) / (Caught * 20 + 10000))
        
                  Where "Caught" is 1 for each unique pokemon, + .5 for each unique Shiny.
                  Where "Attack" is your total pokemon Attack Power.
```

### CODE REVIEW

**Review by anapple96 — CHANGES_REQUESTED** [review]
That issue was opened roughly a year ago. Thing changed. I'm not sure the same thing will work now

**Comment by anapple96** [comment]
> That issue was opened roughly a year ago. Thing changed. I'm not sure the same thing will work now

To further clarify on this. This was created when Proteins, Queue and Kalos + most special forms weren't a thing. Which means attack were relatively low and the Pokemon count wasn't that high. The attack skyrocketed after the addition of Protein and queue. The same thing also happened with the Pokemon count, with Kalos and all the new special forms. Assume the player is halfway through Kalos and has roughly 100-200 shinies, the effective DPS of that player will double if they can click moderately fast (18-20 CPS)

**Comment by benanderson1** [comment]
> 
> 
> That issue was opened roughly a year ago. Thing changed. I'm not sure the same thing will work now

No problem, feel free to close this PR. 

I only grabbed it because it had an approved label. I'll try some of the others instead.

**Comment by RedSparr0w** [comment]
Sorry, I forgot to update the issue and only posted on the other PR that was open at the time.
We ran a poll in the Discord for a few different scaling methods in the squad channel:
<details>
<summary> Links from the discord poll </summary>

_Refer PR here:_
_<https://github.com/pokeclicker/pokeclicker/pull/1109>_
_Refer graph here:_
_<https://www.desmos.com/calculator/0shwcwveyl>_
_See what your click attack would be:_
<https://codepen.io/RedSparr0w/full/PoGYbaM>
</details>

image


The winning formula was this:
_(which is pretty much the same as the formula you've already done, just with added Achievement bonus)_
```js
// TP = Total Pokemon
// TSP = Total Shiny Pokemon
// CPA = Current Total Attack
// CAB = Current Achievement Bonus
bothClickAttack = (TP, TSP, CPA, CAB) => {
        TP = TP + (TSP / 2);
        CAB = (1 + CAB / 100);
        let clickAttack = Math.pow(TP, 4 / 3) + ((CPA * TP * CAB) / (TP * CAB * 20 + 10000));
        return Math.floor(clickAttack || 0);
}
```

For example with my current Challenge save:
_where click attack doesn't matter anyway 😓_
image

**Comment by benanderson1** [comment]
Was that formula voted on post-Proteins and other things mentioned in Apple's post?

Here's my stats with that new formula, for another data point (at endgame, everything cleared and grinding achievements):
image

**Comment by RedSparr0w** [comment]
Mmm, yeah it is quite OP, even with just the Pokemon attack it is quite high, maybe we should just scale with Achievement % for now, as that's quite a bit lower, and was 2nd in the poll, then relook at it later on.

**Comment by benanderson1** [comment]
Current Click Attack: 13367

With scaling with Achievement Bonus:
Click Attack: 60797

20 CPS now puts me at just 1/3 of my regular DPS. That doesn't seem overly OP, especially since it is a reward for grinding achievements and not the default.

I pushed a commit to update the formula in case you want to play around with it / merge it.

**Review by RedSparr0w — APPROVED** [review]
Looks good, thanks for the PR!

We can review if this needs to be modified later on, but should be a good base and make click attacks a lot more useful.

**Pull request merged**
