### PR TITLE
Johto dungeon trainers

### PR DESCRIPTION
**Pull request by Ultima1990**
It begins...

### CODE REVIEW

**Comment by Ultima1990** [comment]
Team Rockets Hideout in Mahogany is here! Immediately undoing my work in #1634 by adding a new dungeon that exists only in a town. There's just no space around Mahogany.

Anyway, requirements are updated to include the hideout. Everything that was once locked behind Mineral+Glacial is now locked behind the hideout, which itself is of course locked behind Mineral+Glacial. Did the update.ts thing to move the dungeon indexes.

This is where I hit a bit of a roadblock. I have to think about how to handle the Goldenrod situation. That place is effectively 3 dungeons. Radio tower, underground tunnel/warehouse, and then radio tower again. So yea, gotta figure that out. Currently I'm leaning towards just smashing that all together into one dungeon. Let me know any other ideas.

**Comment by Askellown** [comment]
it makes sense to me to just make it Radio Tower, since the only battle worth talking about in the UG path (Rival) not really being relevant in Pokeclicker

**Comment by Ultima1990** [comment]
Dramatic finish!

**Review by RedSparr0w — APPROVED** [review]
Looks good, thanks for the PR!

**Pull request merged**
