### PR TITLE
Add all translate keys in the settings menu

### PR DESCRIPTION
**Pull request by Montmo90**
## Types of changes

- Bug fix
- New feature
- UI improvement

### CODE REVIEW

**Comment by Montmo90** [comment]
Hello thank you.
I don't see how to follow your advice.

**Comment by Montmo90** [comment]
Good idea, I thought about doing that, but I'm going to have to modify all the SettingOption calls?

What I had done before allowed me to modify the addition of translate keys over time.

**Comment by Montmo90** [comment]
Good idea, I'll see if I can get it right :D

My bad, I was thinking of deleting the file from my PR...

**Comment by CypherX** [comment]
I will be closing this as you did not include any information about your change and completely ignored the PR template. Feel free to update the original comment and re-open this.

**Comment by Montmo90** [comment]
Hi @CypherX,
I modified the PR template. Does this suit you?
I'm sorry, I can't open this PR.

**Pull request closed without merging**
