### PR TITLE
Some balance tweaks for the new loot system

### PR DESCRIPTION
**Pull request by NiCeDiCe90**
- removed "Passho" from Kantos diglett cave and added the "Wiki" berry instead
- increased chance to find Dome and Helix fossils in Mt. Moon (weight: 0 -> 1)
- removed Omanyte and Kabuto as boss encounter from Mt. Moon

### CODE REVIEW

**Comment by scolpitts536** [comment]
I'm okay with everything except removing the bosses, they are there in-game.

**Comment by NiCeDiCe90** [comment]
I don't understand your point.
In the original games you only get the fossils in Mt. Moon. That will be the case in Pokeclicker too with this change.

**Comment by scolpitts536** [comment]
Well you would be making them underground or mt.moon/cerulean cave chests and ngl i already know how bad the complaints for not getting underground rng is with fossils.

**Comment by NiCeDiCe90** [comment]
People always complain but:
In Kanto these fossils are the only fossils in the underground pool so it's very likely to get them early.
With the dex requirement removed you don't need them to move on. There are a also lot of dungeons where you get these fossils later in the game.
So there are plenty of ways to get them.

**Comment by scolpitts536** [comment]
Hmm fair point.

**Comment by RedSparr0w** [comment]
Any changes should still be balanced around the dex requirement being a thing, as that's still the default way to play.

We could make it that when you defeat the dungeon for the first time you are awarded 1 of the fossils though as you would normally get 1 in game.

**Review by RedSparr0w — APPROVED** [review]
Looks good, thanks for the PR! 👍

**Pull request merged**
