### PR TITLE
Protein updates

### PR DESCRIPTION
**Pull request by RedSparr0w**
Nerf protein (5 per region, down from 10)
Is now used from within the item menu
Removed from the hatchery
Fixed category list showing in hatchery

### CODE REVIEW

**Comment by KrushGames** [comment]
honestly this is probably fair. But 1 question: does this take away the effects of protein we have already used?

**Comment by RedSparr0w** [comment]
> honestly this is probably fair. But 1 question: does this take away the effects of protein we have already used?

Yes, but as with most updates it refunds any overused Proteins.

**Comment by RedSparr0w** [comment]
> honestly this is probably fair. But 1 question: does this take away the effects of protein we have already used?

Oh, nevermind, misread your comment.
Nope, it won't reduce the current attack gains you already have, but will reduce the total proteins used on Pokemon, so in the future they won't be gaining that same amount as before.

**Comment by KrushGames** [comment]
actually you may have misread it, but it answered what i wanted to ask perfectly. I phrased the question wrong too

**Pull request merged**
