### PR TITLE
Added shadow icons

### PR DESCRIPTION
**Pull request by Jaaslet**
The icon shows up in the hatchery and the pokemon list.
We are using pokeballs for the other places, where i wanted to add them. And i don't know what to do about it, right now...
image
image

### CODE REVIEW

**Comment by Aegyo** [comment]
Two questions:
1. Why aren't the image files square? They don't align nicely with the megastone images like this
2. Nothing in pokedex?

**Comment by Jaaslet** [comment]
> Why aren't the image files square? They don't align nicely with the megastone images like this

I did not make the images, so i have no idea. I can ask for a squared one?

> Nothing in pokedex?

Pokedex uses pokeballs and not shiny icons to show shiny status. I don't know how i want to handle that yet

**Comment by Aegyo** [comment]
Given your image, for pokedex I was expecting a shadow icon in the spot below where we have the megastone icon

**Comment by DraKay** [comment]
The shape was the default, I could cut it, but tomorrow

**Comment by Jaaslet** [comment]
> Given your image, for pokedex I was expecting a shadow icon in the spot below where we have the megastone icon

I will do that then. We might change it later, but then we at least have something

**Comment by DraKay** [comment]
purified
Shadow
The square versions

**Comment by Jaaslet** [comment]
New icons and added to pokedex! Ready for review again!

**Comment by Aegyo** [comment]
The images in the PR are black, not sure what happened there.

**Comment by Jaaslet** [comment]
Images fixed. Not sure what happened either...

**Review by Aegyo — APPROVED** [review]

**Pull request merged**
