### PR TITLE
Ace Trainer Quinn additional dialogue to help with Zero's Quest

### PR DESCRIPTION
**Pull request by LuchoDreamer**
This PR adds one line of dialogue to give a hint on how to trigger Zero's Ambition quest, because it gets asked almost daily.

### CODE REVIEW

**Comment by Jaaslet** [comment]
I think `I doubt he'd be able to help you unless you could help him find a way to get there..` or something would make more sense. The current sounds a bit weird. It sounds like you need to bribe hm or something

**Comment by LuchoDreamer** [comment]
Well, the quest is about you helping Zero get into the Distortion World, not about Zero helping you. Maybe something like` I doubt he'd be interested in _talking to_ you unless you could help him find a way to get there..`

**Comment by LuchoDreamer** [comment]
Perfect, change done

**Review by Jaaslet — APPROVED** [review]
Looks good. Thanks for the PR

**Pull request merged**
