### PR TITLE
Updated breedingModal.html

### PR DESCRIPTION
**Pull request by unclebanks**
* Added dex number to pokemon in hatchery selector

### CODE REVIEW

**Comment by RedSparr0w** [comment]
I'm not sure about this one, as some names are already quite large, and this just expands the problem.

I think this would be better as an option for the Hatchery "Display Value":
image

**Comment by unclebanks** [comment]
I agree but multiple people specifically requested this so would it be ok to set those to be able to select multiples? Or lock it to just allow dex number with whatever other standard was picked?

**Comment by unclebanks** [comment]
I cant find the file to edit that. :/ Can you give me the name of it?

**Comment by RedSparr0w** [comment]
> I cant find the file to edit that. :/ Can you give me the name of it?

The main area is:
`src\scripts\settings\SortOptions.ts`

And you will also need to add it to:
`src\scripts\settings\Settings.ts`

**Comment by RedSparr0w** [comment]
Wrong file, updated above 😅

**Pull request closed without merging**
