### PR TITLE
P2 Buff

### PR DESCRIPTION
**Pull request by anapple96**
Realized P2 was extremely weak post-push, added a bunch of tough Pokemons and added Arceus (steel) as a reward (I feel like steel is appropriate here, as it's a lab)

### CODE REVIEW

**Comment by anapple96** [comment]
Now that I think about it, Arceus-Steel may not be a great idea

**Comment by Ultima1990** [comment]
I'm not a big fan of putting Arceus in there either. Also bloody hell that's a big boss pool.

**Comment by anapple96** [comment]
Should be OK for review now

**Review by RedSparr0w — APPROVED** [review]
Looks good, Thanks for the PR

**Pull request merged**
