### PR TITLE
Migrate negative Pokemon to decimals

### PR DESCRIPTION
**Pull request by apple096**
I lied.
This PR migrates negative ID Pokemons to decimal.
There's also an update function for it

### CODE REVIEW

**Review by amative1 — CHANGES_REQUESTED** [review]
New ID #s for Mega forms are the same as those for the clone forms. Is this intentional, or an oversight?

**Comment by apple096** [comment]
Oversight, won't hurt anytime soon but it's good to have them changed soon-ish

**Review by amative1 — APPROVED** [review]

**Comment by RedSparr0w** [comment]
I feel like we should also move the Pokémon in PokemonList to be next to the base Pokémon with the IDs, just so it's less likely we end up with Pokémon having the same IDs in the future?
_as what almost happened with the megas/clones_

**Comment by RedSparr0w** [comment]
I've removed the Mega changes from this PR for now,
Only updates the Event Pokémon.
Moved the event Pokémon to be next to their base forms in PokemonList.
Updated the Pokémon & Shiny Pokemon image names.
Updated the Update code to make use of @Jaaslet code from #1833 so it updates the statistics too.

**Review by RedSparr0w — APPROVED** [review]
Thanks for the PR 👍

**Pull request merged**
