### PR TITLE
Migrate LogBook modal rendering to React

### PR DESCRIPTION
**Pull request by Aegyo**
An example of how we could migrate to rendering with react, without having to rip out all the knockout code we have.
Related to #783

The ko-store library unfortunately didn't work out, my guess is because we are using a global ko object from an included script which didn't mesh with the ko the library imports. Luckily, it is licensed under MIT and the code is quite small, so I just copied what we need (useComputed, useForceUpdate, useMemoWithDisposer)

I've added two "hooks" based on redux -> `useGame` is sort of like redux's `useStore`, and `useSelector` is like the redux hook of the same name. These are used for accessing some piece of App.Game, without needing either a global variable or passing it down through every component manually. A "selector" in our context is just a function that grabs some observable (or computedObservable) when given a game object, and the finding and passing of a game object is handled automagically for you with `useSelector`.

I think with this particular modal, I would move all of the filter stuff into react state, since it is really only to do with this bit of the UI. I've left it as knockout for now just to show how we might do other things.

Other modals will be easy to absorb into the ReactApp component, but other pieces of the UI might be an issue since React will want to take control of all its children. We might be able to have multiple react bindings, one for each UI column, and have them gradually absorb their surroundings until they meet at the top of the DOM and can be merged together.

### CODE REVIEW

**Comment by RedSparr0w** [comment]
I don't have any previous experience in React but from what I can see this seems to work great.

I assume we will only be able to convert modules to react components?
So something like the quests modal wouldn't work with this until we move/convert it to modules?

As far as I've seen React performance is a ton better than Knockout, so I think we should definitely move forwards with this.

**Comment by RedSparr0w** [comment]
Also is it worth moving static content to react such as the FAQ modal?

**Comment by Aegyo** [comment]
I think we can reactify non module code, it would just need a little extra work mocking the type on GameShim. I'll try that out with Quests tomorrow to get an idea of how difficult that might be.

Re: moving static content - it is probably worth doing so for anything that can be simplified with a shared component (eg, modal) or which we might want to have dynamic content in the future (translations?)

**Comment by Aegyo** [comment]
Integrating the Sortable drag + drop functionality might also be a pain point, will have to look into that too

**Comment by RedSparr0w** [comment]
> I think we can reactify non module code, it would just need a little extra work mocking the type on GameShim. I'll try that out with Quests tomorrow to get an idea of how difficult that might be.

I think we can probably just ignore non module code for now, I'm trying to slowly move it all over, there isn't a whole ton left, and anything that we move to react we can just move to modules at the same time (where possible)

**Comment by Aegyo** [comment]
Closing as I've changed my mind on using react, see comment in the linked issue

**Pull request closed without merging**
