### PR TITLE
Trainer now shows up in temp and gym battle

### LINKED ISSUE #1238: [SUGGESTION] Add Gym Leader Images to Gym View
In #1219, I've added some commented-out code in `gymView.html`

```HTML
        <div>
            <!-- TODO: HLXII - Add after all Gym Leader images are formatted correctly
            <div style="position:absolute; left:65%;">
                <img height=80px data-bind="attr:{ src: GymBattle.gym.imagePath }"/>
            </div>
            -->
            <img class="enemy" data-bind="attr:{ src: PokemonHelper.getImage(GymBattle.enemyPokemon(), GymBattle.enemyPokemon().shiny) }" src=""/>
        </div>
```

This will display the Gym Leader sprite during the Gym battle, much like how the Trainer images will appear during Trainer battles. The main issue with this is that currently some of the Gym Leaders do not have good images to display in the view.

I'm currently assuming the Gym Leader images are 80x80 pixels. If this is the case, they will be displayed correctly:
image

If they are smaller, or aren't pixel art at all, it looks bad:

image
Looks slightly blurry due to the image being 64x64.

image
lol.

To fix this, we need to update the Gym Leader images to be 80x80 pixel art for every Gym Leader.

### PR DESCRIPTION
**Pull request by Jaaslet**
Trainer now shows up in temp and gym battle, just like dungeon trainers.
Added optional parameter to temp battle, because we don't want it to show up places like the rampaging pokemons in Galar.
Also the two wormholes now uses the same images
Closes #1238

### CODE REVIEW

**Comment by Aegyo** [comment]
Got some conflicts, but looks fine otherwise.
Should Aipom Alley and Possessed Mewtwo also be hiding the trainer?

I just searched for any temp battle with a pokemon in the name not hiding the trainer
```js
Object.keys(TemporaryBattleList).filter(
  k => k.split(' ')
        .filter(w => w != Number(w))
        .some(w => pokemonMap[w].id !== 0))
        .filter(k => !TemporaryBattleList[k].optionalArgs?.hideTrainer
)
```
```js
Array [ "Aipom Alley", "Possessed Mewtwo" ]
```

**Comment by DataCrusade** [comment]
> Got some conflicts, but looks fine otherwise. Should Aipom Alley and Possessed Mewtwo also be hiding the trainer?
> 
> I just searched for any temp battle with a pokemon in the name not hiding the trainer
> 
> ```js
> Object.keys(TemporaryBattleList).filter(
>   k => k.split(' ')
>         .filter(w => w != Number(w))
>         .some(w => pokemonMap[w].id !== 0))
>         .filter(k => !TemporaryBattleList[k].optionalArgs?.hideTrainer
> )
> ```
> 
> ```js
> Array [ "Aipom Alley", "Possessed Mewtwo" ]
> ```

Yep, Aipom Alley and Possessed Mewtwo hiding the "trainer" is correct

**Comment by Aegyo** [comment]
They are not currently being hidden
Screenshot_2022-09-09_00-00-32

Screenshot_2022-09-09_00-01-04

**Comment by DataCrusade** [comment]
oh hmm idk then, ask eugene171 on the discord

**Comment by Jaaslet** [comment]
I found a couple of more than should be hidden. I had just forgotten to keep this PR up to date, when new stuff where merged. But it should be fixed now

**Review by RedSparr0w — APPROVED** [review]
Looks good, thanks for the PR! 👍

**Pull request merged**
