### PR TITLE
Unova dungeon trainers

### PR DESCRIPTION
**Pull request by Ultima1990**
This adds new sprites for:

Ace Trainer (male+female)
Backpacker (male+female)
Battle Girl
Cyclist (male+female)
Doctor
Fisherman
Gentleman
Guitarist
Janitor
Nurse
Nursery Aide
Pokéfan (male+female)
Pokémon Breeder (male+female)
Pokémon Ranger (male+female)
Preschooler (male+female)
Psychic (male+female)
School Kid (male+female)
Socialite
Team Plasma (colress)
Team Plasma (ghetsis)
Team Plasma (shadow)
Team Plasma (zinzolin)
Team Plasma Grunt (male+female)
Twins
Veteran (male+female)
Worker
Worker (ice)

So for any other regions make sure to not add these sprites. Save yourself some trouble.

This PR is not done, I want to add some more dungeons.

### CODE REVIEW

**Comment by Ultima1990** [comment]
Balancing still needs to be done.

**Comment by Matipou2006git** [comment]
i there still some sprite missing? i can try making some if you want

**Review by RedSparr0w — CHANGES_REQUESTED** [review]
Looks good, just needs a couple of changes:
Team Plasma Assault needs to be added to the map image and svg.
Update.ts needs the new dungeon indexes added.

**Review by RedSparr0w — APPROVED** [review]
👍 Looks good, thanks for the PR!

**Pull request merged**
