### PR TITLE
Near Space Dungeon Fixes

### PR DESCRIPTION
**Pull request by Farboo171**
Locks Deoxys alt forms behind already having obtained them

Adds a Mythic tier chest item: Carbos

Changes base difficulty to Kalos difficulty.

### CODE REVIEW

**Comment by Razorflamekun** [comment]
Personally, I don't believe that the dungeon itself should be Kalos difficulty if it is in Hoenn.  Having it Kalos Difficulty HP-wise, is fine, but I don't agree with making everything else about it Kalos difficulty.

**Comment by Jaaslet** [comment]
It's the same we did for sevii4567

**Comment by Razorflamekun** [comment]
Ok, if that's the way it has to be, then I guess I have to accept it.

**Review by Jaaslet — APPROVED** [review]
Looks good. Thanks for the PR

**Pull request merged**
