### PR TITLE
Singularize eggs in Hatch egg quest when you only need to hatch one

### PR DESCRIPTION
**Pull request by CooldudeOmega**
I sort of did a copypaste from berries with an ok amount of modification so if it doesn't work please help fix it since I'm sure it isn't right the first time

### CODE REVIEW

**Comment by CooldudeOmega** [comment]
check failed, let me go fix that I guess

**Comment by CooldudeOmega** [comment]
No way, it actually looks like it works, I'm just gonna wait for a review then.

**Comment by CooldudeOmega** [comment]
Does the plural of egg need to be defined in the code? I saw a pr about berry pluralization having berry plural defined in dungeon something idk

**Comment by Aegyo** [comment]
That can be done in translation files eventually

**Review by Jaaslet — APPROVED** [review]
Looks good. Thanks for the PR

**Pull request merged**
