### PR TITLE
Adding a little secret

### PR DESCRIPTION
**Pull request by NiCeDiCe90**
I hope it's ok and I didn't miss anything.

### CODE REVIEW

**Comment by RedSparr0w** [comment]
This would probably be better as a Valentines event?

**Comment by NiCeDiCe90** [comment]
> This would probably be better as a Valentines event?

That was my original idea for it but I was told we don't want any more RL related Events. 
I don't mind changing it to an Event encounter if you think that would be the better way.

**Comment by Ultima1990** [comment]
Can maybe grab something from this list https://bulbapedia.bulbagarden.net/wiki/Category:Festivals_and_holidays

**Comment by JapuDCret** [comment]
the [Pokemon Flower Arrangement](https://m.bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_Flower_Arrangement) sounds appropriate

**Comment by RedSparr0w** [comment]
👍 Yeah some sort of event, as we don't have any other non cannon encounters that aren't events currently.

**Comment by NiCeDiCe90** [comment]
So I found this one among the "in lore" Festivals: https://bulbapedia.bulbagarden.net/wiki/Kids_Day

But its a little weak. 

According to the real life Kids day in Japan it's part of a chain of multiple holidays called "golden week"
My suggestion for an ingame event would now be the "golden week event" from April 29th to May 6th.
would that be ok for you?
Just need to decide how to add it? (Another...) Kanto roamer?

**Comment by RedSparr0w** [comment]
Doesn't need to be a Kanto appearance IMO

**Comment by NiCeDiCe90** [comment]
Not a little secret anymore.
It's now a little event.

**Review by RedSparr0w — APPROVED** [review]
Looks good, thanks for the PR! 👍

**Pull request merged**
