### PR TITLE
Fix near berry strict mutation

### PR DESCRIPTION
**Pull request by HLXII**
Added shallowEqual

### CODE REVIEW

**Comment by RedSparr0w** [comment]
This will not work if the keys are in a different order though:
```js
a = {
  'test2': 2,
  'test1': 1,
}

b = {
  'test1': 1,
  'test2': 2,
}

console.log(JSON.stringify(a)) // {"test2":2,"test1":1}
console.log(JSON.stringify(b)) // {"test1":1,"test2":2}
JSON.stringify(a) === JSON.stringify(b) // false
```

**Comment by HLXII** [comment]
That doesn't seem to be the case for numbers?

image

**Comment by RedSparr0w** [comment]
Numbers seem to vary from browser to browser, I would rather use a deep/shallow equal than stringify, just so we can be certain it's comparing them correctly.

**Comment by RedSparr0w** [comment]
And then we can also use the same function in the future if needed anywhere else.

**Comment by HLXII** [comment]
Added

**Review by RedSparr0w — APPROVED** [review]
👍 Changes look good to me, Thanks for the PR!

**Comment by RedSparr0w** [comment]
Whoops, I forgot to merge this 😅

**Pull request merged**
