### PR TITLE
Change meteorite "mega stone" image

### PR DESCRIPTION
**Pull request by DraKay**
## Description
Change the 24x24 pixl meteorite image for a 80x80 one using mega stone style

## Motivation and Context
The current image is 4 times smaller that other mega stones and have a totally different style, so was logical to infy them

## Types of changes

- UI improvement

### CODE REVIEW

**Comment by DraKay** [comment]
Changed the image for the one we talked in crew

**Comment by Jaaslet** [comment]
Credits!

**Comment by DraKay** [comment]
Upsy... Done

**Review by Jaaslet — APPROVED** [review]
Looks good. Thanks for the PR

**Comment by osherwott** [comment]
For future reference, this design is based off of its depiction in the web series: Pokémon Evolutions episode 6 - The Wish

image

**Pull request merged**
