### PR TITLE
Oak Item Loadouts

### PR DESCRIPTION
**Pull request by kushpatel0703**
This PR is meant to hold changes relating to adding OakItem Loadouts. Currently this is a work-in-progress, but I will add more as I get time to write code. Would love to have feedback, especially on front-end since that is not my forte.

### CODE REVIEW

**Comment by kushpatel0703** [comment]
image

This is what it looks like so far. It's horrendous, I know, please let me know how to fix it. I am a backend developer lol

**Comment by kushpatel0703** [comment]
Done:
Basic Logic Is Working (adding/clearing the loadouts)
Very Rough UI

To-Do:
Fix UI
Fix highlighting in OakItemLoadoutModal (only highlight what is in each loadout)
Add remove item logic (not clear loadout)
Refactor to use defined functions

**Comment by RedSparr0w** [comment]
I feel like it probably takes up too much space being in the main screen instead of the current oak modal/a new modal

**Comment by kushpatel0703** [comment]
The only thing on the main screen will be the 1, 2, 3, and Setup button. Setup button leads to a new Modal

**Comment by silasary** [comment]
Take Setup off the main screen altogether.   Put "Save to loadout" on the edit modal

**Comment by kushpatel0703** [comment]
Okay guys, as per requested, I moved the logic to a tabinated modal now. I still am really bad with front-end so I have broken some stuff. 

Things that need to be done:
Fix spacing issues in modal tabs
Why did all the icons get so small in 2nd tab, only the lord knows
Highlighting is still not working (now nothing is highlighted as opposed to everything)
keyboard shortcuts (??)

If anyone has any insight as to how I can fix these or make them look better please let me know

**Comment by RedSparr0w** [comment]
A couple things that still need to be done is:
- Not allowing applying layouts if in a `No Oak Item` challenge
- Also hide the buttons if in a `No Oak Item` challenge

**Comment by kushpatel0703** [comment]
Thanks to Red, I think this is ready for merge :) If people want to check it out and let me know if there is something that might be better changed, please do.

**Review by RedSparr0w — APPROVED** [review]
👍 Looks good, thanks for the PR!

**Pull request merged**
