### PR TITLE
Buff Diglett's Cave

### PR DESCRIPTION
**Pull request by Ultima1990**
Diglett's Cave is still balanced like a route 2 dungeon. Both in HP and cost. It should be harder than Mt. Moon but not as hard as Rock Tunnel.

### CODE REVIEW

**Comment by Symi001** [comment]
I guess there won't be a way of putting it in between in terms of road ? Meaning it'll yield way less exp ?

**Comment by Ultima1990** [comment]
The dungeon is now marked as route 11 rather than route 2. If that has any effect on dungeon exp then Diglett's Cave exp gain also got buffed. Tho TBH I have no idea how that works.

**Comment by Symi001** [comment]
If it's marked as route 11 it'll also make the exp change, perfect, sry for the bother ^^

**Review by Jaaslet — APPROVED** [review]
Looks good. Thanks for the PR

**Pull request merged**
