### PR TITLE
Implement Pink Bow held item

### PR DESCRIPTION
**Pull request by kittenchilly**
Adds a fairy type boosting held item, the Pink Bow. Since there isn't a fairy type boosting item in canon, this is based on the abandoned held item from Gen 2 which fits fairy type pretty well. Currently obtainable in Johto Radio Tower (It was located there in canon in gen 2), Kalos Pokemon Village (pixie plate is located here, also fairy types), Alola Trainer School (Pink bow feels like it'd fit in school areas, something school children would wear), Alola Mina's Houseboat (fairy type theme).
Uses a custom pink bow image made by DraK4y.

### CODE REVIEW

**Comment by DataCrusade** [comment]
We might want to use a different image or have a custom image made for it, since I believe that's a ribbon image and we've only used ribbons for advanced challenges. I'm just nitpicking though

**Comment by kittenchilly** [comment]
Yeah, I used the Best Friend's Ribbon since it was the most fitting official artwork I could find. If someone wants to make a custom one perhaps based on a mystery dungeon design, be my guest.

**Comment by kittenchilly** [comment]
New custom Pink Bow sprite by DraK4y!
image

**Comment by Jaaslet** [comment]
Credits!

**Review by Jaaslet — CHANGES_REQUESTED** [review]
No changing the docs folder! (so you need to revert it)
I have removed the bow from the trainer's school, as it was obtainable too many places in Kalos/alola, and the school seemed like the weakest reason.
But other than that, it looks good

**Review by Jaaslet — APPROVED** [review]
Looks good. Thanks for the PR

**Pull request merged**
