### PR TITLE
Added Furfrou (star)

### PR DESCRIPTION
**Pull request by Jaaslet**
Tater gave me this amazing idea to add a furfrou as a shard trade... So i did it...
Found in Parfum Palace. Numbers might be a bit high, but it's a lategame grindy pokemon (like the rest). And if it's too high, we will nerf it in a later patch, and look like heroes.
Also turned Parfum Palace into a town. There was no reason for it to be a dungeon (did not add anything), and there are no encounters in the game.

### CODE REVIEW

**Review by RedSparr0w — APPROVED** [review]
Looks good to me, thanks for the PR! 👍 

Just double checking, `Furfrou` is still obtainable outside of `Parfum Palace`?

**Comment by Qwertypop04** [comment]
> Just double checking, `Furfrou` is still obtainable outside of `Parfum Palace`?

Yep, it's on Kalos Route 5

**Comment by CorgiOnNeptune** [comment]
The update function needs to be moved to 0.9.10, right?

**Comment by RedSparr0w** [comment]
> Yep, it's on Kalos Route 5

Awesome, thanks 👍 

> The update function needs to be moved to 0.9.10, right?

Nice catch 👍

**Comment by RedSparr0w** [comment]
Sorry, 1 last thing, should the town be changed to a Pokémon Center on the map rather than how it is at the moment?
image

**Pull request merged**
