### PR TITLE
Hisui sprite and data

### PR DESCRIPTION
**Pull request by lenormandSeb**
- All images are from serebii. (i don't find "potable" sprite execpt on serebii)
- Some pokémons stat need adjustment (egg step and exp).
- All forms and evolutions are comment.
- Some evolution are based on some condition than cann't be use here, so i use the `regionLevelEvolution` for those.

### CODE REVIEW

**Comment by zyx-xyzzy** [comment]
Gen 6+ mons on PokéClicker use custom-made 2D sprites in the style of previous gens, not pictures of 3D renders like those serebii ones, so those images won't work.

**Comment by DataCrusade** [comment]
Obsidian Stone should be Black Augurite as that's what its called in PLA

**Comment by lenormandSeb** [comment]
@zyx-xyzzy 2D sprite are not my speciality :smile: but they work (horribly, yes but, pending the goods one, testing with sprite can be made)
@DataCrusade Done ! (translation word by word, don't check if english had this name :sweat: ) here : [5b56898](https://github.com/pokeclicker/pokeclicker/pull/2653/commits/5b568982b373380385e20f7b5beb907b9ce8449f) and [45ffb50](https://github.com/pokeclicker/pokeclicker/pull/2653/commits/45ffb5076709b7dc69571b9e10974278a1e529be)

**Comment by DataCrusade** [comment]
all good, no worries! thank you!

**Comment by Ultima1990** [comment]
I say we hold off on this because adding these mons to the data now results in them showing up in Frontier, which just results in endless begging for Hisui to be added and the mons to be obtainable. I don't feel like rushing that. At this stage we're not even sure _how_ we'll add Hisui. We haven't even started creating the place. No need to encourage people to try to push us to do it faster.

**Comment by lenormandSeb** [comment]
@Ultima1990 
It's not my goal to rush you or force you. :smile: 
It was just for you advance on the addition of the data of the forms of hisui.

But if the fact of having added the names makes them appear in the Frontier, I understand the concern.

Maybe I should close it straight away and you can cherry-pick some commit when you're ready for the region?

**Comment by Jaaslet** [comment]
I think someone already has a branch ready with the correct sprites. We just need to figure out how and when we want to add them

**Comment by Jaaslet** [comment]
We have talked a bit about it, and we will not be accepting any Hisui PRs, until someone has a detailed plan, that we agree on, and we have someone who wants to start working on the full project.
I will close this PR

**Pull request closed without merging**
