### PR TITLE
Remove Mahogany Fighting Egg

### PR DESCRIPTION
**Pull request by Ultima1990**

### CODE REVIEW

**Comment by RedSparr0w** [comment]
Is there a reason for the removal?

**Comment by Qwertypop4** [comment]
There's no reason to have the same egg twice in the same reason

**Comment by Ultima1990** [comment]
It's a duplicate. The same egg is also in the CianwoodCityShop, which makes more sense since Cianwood has the fighting gym.

**Review by RedSparr0w — APPROVED** [review]
Sweet, thanks for the PR 👍

**Pull request merged**
