### PR TITLE
fix(lag): Ratelimit sorted achievement list, only update when modal open

### LINKED ISSUE #3228: [BUG] One hitting enemies by click is triggering the update of the achievement lists
**Info**
 - OS: [Android 12
 - Browser [Chrome]
 - Version [e.g. `v0.10.0`]

**Description:**
Whenever you defeat a Pokemon and the game loads a new one, if your achievements list is sorted by and value other than Default, there is a call to update every achievement in the list.
This is specially noticeable when one-hitting enemies very fast.

**Steps to Reproduce:**
1. Sort the achivements list by progress
2. Defeat pokemon on a route you can one-hit them by click attack
3. Profile the application and notice the calls to update the achivements list.

**Expected Behavior:**
The achievements list should have a rate limit even when sorted.

**Additional Information:**
Screenshot from 2022-10-21 10-24-05
Screenshot from 2022-10-21 10-25-23
Screenshot from 2022-10-21 10-25-36

### PR DESCRIPTION
**Pull request by Aegyo**
Fixes #3228

@erzads could you confirm this fixes the lag you were seeing?

### CODE REVIEW

**Comment by erzads** [comment]
@Aegyo sorry for the delay. I just tested your branch on my mobile and sorted the achievements by progress. After that, I did a quick test click attacking and one shoting enemies. The lag no longer happens, all good!

**Review by Jaaslet — CHANGES_REQUESTED** [review]
It now takes a long time for the filters to apply. I don't know if the rateLimit is too high?
But the code looks good and stuff still works. I don't have the lag myself, so i just need to trust erzads for that part

**Comment by RedSparr0w** [comment]
Maybe we should add some sort of `Loading` animation type thing for when the options change but it hasn't updated.
Or maybe we should do a force update when those options change.

**Comment by Aegyo** [comment]
> It now takes a long time for the filters to apply. I don't know if the rateLimit is too high? But the code looks good and stuff still works. I don't have the lag myself, so i just need to trust erzads for that part

Lowered the rate limit to 100ms, seems ok now? Majority of the lag fixing is coming from only calculating while the modal is open, so this shouldn't reintroduce much if any lag.

**Review by Jaaslet — APPROVED** [review]
Looks good. Thanks for the PR

**Pull request merged**
