### PR TITLE
Joey!

### PR DESCRIPTION
**Pull request by PixLSteam**
Joey.

### CODE REVIEW

**Comment by CypherX** [comment]
Joey.

**Review by Jaaslet — CHANGES_REQUESTED** [review]
The temp battle list in GameConstants is sorted, so the battle needs to be put up somewhere with the other johto battles. Other than that, it looks good

**Comment by PixLSteam** [comment]
> The temp battle list in GameConstants is sorted, so the battle needs to be put up somewhere with the other johto battles. Other than that, it looks good

But Joey is the best, he deserves that spot :/

**Review by Jaaslet — APPROVED** [review]
Looks Joey! Thanks for the Joey!

**Pull request merged**
