### PR TITLE
Feature/new challenge shiny route

### PR DESCRIPTION
**Pull request by lenormandSeb**
Creating real challenge for the "Shiny Quest Route" that some player do

### CODE REVIEW

**Comment by Someonealive-QN** [comment]
A pr already exists for this challenge 😅 #2538

**Comment by DataCrusade** [comment]
Pretty sure this is different @Someonealive-QN. I assume this is you have to get all shinies on a route to progress to the next route. Shiny dex required is you have to get every shiny in the region before you can progress to the next.

**Comment by Jaaslet** [comment]
Data is correct

**Comment by lenormandSeb** [comment]
I took a look at the PR, they are different but I think my PR can be, either integrated with Jasslet's code, or closed to avoid any confusion :thinking:

**Comment by DataCrusade** [comment]
can't make a commit to this PR, but made adjusted the text to improve the grammar

Challenges.ts line 19
`        shinyCompleteRoute: new Challenge('Shiny Complete Route', 'Requires every shiny Pokémon on a route to be captured before moving on to the next route.'),`

Update.ts line 1044
`                if (await Notifier.confirm({ title: 'Shiny Complete Route', message: 'New challenge mode added: Shiny Complete Route.\n\nRequires every shiny on a route to be captured before you may move on to the next route.\n\nPlease choose if you would like this challenge mode to be enabled or disabled (cannot be re-enabled later)', confirm: 'enable', cancel: 'disable' })) {`

MapHelper.ts line 35
`                    message: 'All shinies in the previous route must be caught first.',`

**Comment by Jaaslet** [comment]
Closing for the same reasons as stated in PR #2538.
And i am sorry for not closing 2538 earlier, as it might have made it look like we wanted this PR

**Pull request closed without merging**
