### PR TITLE
Fix/standardize infobox

### PR DESCRIPTION
**Pull request by HLXII**
Previously, we had multiple locations show helpful information using this button:
image
image

However, there are a couple of locations that don't use this standard. I've updated them so it's cleaner for the user to know that "Question mark button in the top right means info".

Hatchery:
Before:
image
After:
image

Damage Calculator:
Before:
image
image

Quest Line:
Before:
image
After:
image

### CODE REVIEW

**Comment by RedSparr0w** [comment]
We need the `x` on modals for mobiles, otherwise it becomes a huge chore trying to close the modals by clicking the background.

Maybe we could move the `?` to the left hand side instead?

**Comment by HLXII** [comment]
The Shard Modal doesn't have the X either? There's a Close button in the footer of all the modals as well

**Comment by RedSparr0w** [comment]
As long as the updated modals have the footer and close button, then it should be fine _(I can't tell from the files changed tab)_.

I don't think we need for it on the Quest Lines though, as it's not really help information, just some minor information/flavor text.

**Review by RedSparr0w — APPROVED** [review]
Looks good 👍 

Thanks for the PR!

**Pull request merged**
