### PR TITLE
Egg Incubator replacing Mystery Egg Key Item

### PR DESCRIPTION
**Pull request by Farboo171**
Name and image of the Mystery Egg key item updated per Issue #2601 to remove confusion with the Mystery Egg egg type.

### CODE REVIEW

**Comment by DataCrusade** [comment]
The image should probably be a sprite to match the rest of the key items although I just noticed that the Pokerus Virus key item isn't a sprite either. I can make a sprite for this tomorrow if you'd like.

**Comment by Ultima1990** [comment]
I do agree that renaming one of the Mystery Egg items is a good idea to avoid confusion. However, I'm not sure Egg Incubator is the way to go, since that is a thing you carry around and hatch eggs in while hatching in our game happens at the hatchery, which is a static location.

**Comment by Farboo171** [comment]
> The image should probably be a sprite to match the rest of the key items although I just noticed that the Pokerus Virus key item isn't a sprite either. I can make a sprite for this tomorrow if you'd like.

Sure! I'm not sure how to sprite-ify images, so that's probably a good idea to be in keeping with the theme.

**Comment by Farboo171** [comment]
I'll look into why this is messing up, and can float some other options besides incubator, sorry for the mess.

**Pull request closed without merging**
