### PR TITLE
Update AchievementHandler.ts

### PR DESCRIPTION
**Pull request by amative1**
Changed text for ball cheevos from Obtain to Purchase, due to some balls now being obtainable via other means.

### CODE REVIEW

**Review by apple096 — CHANGES_REQUESTED** [review]
People seems to forget the Update function, so this change will break 100% of saves

**Comment by amative1** [comment]
Interesting, as testing with multiple save files (both current and a few versions back) show no issues.

**Comment by PixLSteam** [comment]
> People seems to forget the Update function, so this change will break 100% of saves

Wouldn't that only be relevant if the name of the achievements changed?

**Comment by apple096** [comment]
> > People seems to forget the Update function, so this change will break 100% of saves
> 
> Wouldn't that only be relevant if the name of the achievements changed?

Oh this is a description change

**Comment by jk13pclick** [comment]
What does not have an update function and could probably use an update function is #1717, but depending on how this PR goes I may just end up closing that one anyways

**Comment by RedSparr0w** [comment]
Not sure if this is still relevant?
Does the achievement require purchasing them? or just simply obtaining them?

**Comment by amative1** [comment]
Achievement is coded for purchase, which now that we have balls being obtainable in other ways it needed clarified, hence the PR.

**Review by RedSparr0w — APPROVED** [review]
Thanks for following up 👍 
Looks good, thanks for the PR!

**Pull request merged**
