### PR TITLE
Moved the underground "sell all" button to the tab

### PR DESCRIPTION
**Pull request by Jaaslet**
Solves #2052. The button is now at the bottom of the treasure tab.
image

### CODE REVIEW

**Comment by Claygame** [comment]
can you make the button location/size something that cant be pressed accidentally? this huge button right above the Close window button looks easy accident and a devastating one for someone's progress

**Comment by Jaaslet** [comment]
> can you make the button location/size something that cant be pressed accidentally? this huge button right above the Close window button looks easy accident and a devastating one for someone's progress

It's in the bottom of the treasure tab. So you first need to scroll all the way to the bottom.
And the butyon has a confirmation-window, so it should easy to avoid selling all.
Let me know if you still don't think it's enough

**Comment by Claygame** [comment]
> It's in the bottom of the treasure tab. So you first need to scroll all the way to the bottom. And the butyon has a confirmation-window, so it should easy to avoid selling all. Let me know if you still don't think it's enough

ah, with a confirmation box it is good. Thank you for the change ^_^

**Review by RedSparr0w — APPROVED** [review]
Looks good, thanks for the PR! 👍

**Pull request merged**
