### PR TITLE
Add Sinnoh and Alola stones to underground

### PR DESCRIPTION
**Pull request by Ultima1990**
Does what it says on the tin.

Except it doesn't. I'm missing something.
The instruction on UndergroundItemNameType.ts seems to be quite outdated. Maybe that's it.

### CODE REVIEW

**Comment by Ultima1990** [comment]
This is ready. And it now brings back Sun Stone too. Thanks Jaaslet!

**Comment by kittenchilly** [comment]
This PR has been inactive for a while despite looking complete. I'd love if this got revived and looked at again.

**Comment by Jaaslet** [comment]
> This PR has been inactive for a while despite looking complete. I'd love if this got revived and looked at again.

It is fully alive. Just waiting for our (busy) tester

**Comment by Ultima1990** [comment]
10 days ago. Looks plenty alive to me.

**Pull request merged**
