### PR TITLE
Purify chamber now needs exp to purify

### PR DESCRIPTION
**Pull request by Jaaslet**
Each time a pokemon in your party, that is not yet level 100, gets exp, that exp will be added as "flow" to your purify chamber (divided by 1000, to make the numbers smaller).
When you have enough flow, you can purify one pokemon, and the flow resets.
(draft because i still need a formular. Working on it)

### CODE REVIEW

**Comment by Jaaslet** [comment]
Formula added! It looks stupid...
What i tried to do:
First ~10 only takes a couple of minutes of farming in hoenn.
Then it goes slowly up until like 120, where it takes 4 hours per mon in galar.
Last couple of mons takes almost a day in Galar.
I don't understand the formula. Got a friend to help me...
My hope is that the crew will discuss the optimal farming method, do some calculations and then tell if it's too stupid or not.

**Comment by Aegyo** [comment]
No graph? 😞

**Comment by Jaaslet** [comment]
> No graph? 😞

I am not sure I want to see it...
But it's y will just be some big numbers, so not sure if it's super useful?

**Comment by Jaaslet** [comment]
I tried to make a graph that makes sense... It's hard...

**Comment by Jaaslet** [comment]
I was hoping for it to be a bit more smooth around... But yeah, this is what i asked for.
I wanted the last couple to take a long time, without others taking too long.
But the total is 131

**Comment by Farboo171** [comment]
Image added for record keeping's sake

**Comment by Farboo171** [comment]
To codify what was said in discord: I'm down with merging this as-is and balancing before actual release

**Comment by Jaaslet** [comment]
I have changed the formula to Eugenes more smooth curve. I don't think it's correct, but i think it will be a lot easier to discuss and find the correct formula, when the crew starts testing Orre.
So (like Eugene said) i think we should merge this PR and then change the formula before release of Orre

**Review by Aegyo — APPROVED** [review]

**Pull request merged**
