### PR TITLE
Loot fixup observable

### PR DESCRIPTION
**Pull request by jk13pclick**
Pokéballs obtained in dungeons should probably add to the observable, thanks Vic for the report.

### CODE REVIEW

**Comment by RedSparr0w** [comment]
Should we be doing this for berries too?

Not sure if any of the other things are tracked at all 🤔

**Comment by jk13pclick** [comment]
Berries should be tracked as well for quest reasons, might even make berry quests more doable

**Comment by RedSparr0w** [comment]
Ah didn't realise it's already incrementing the berries stats 👍

**Review by RedSparr0w — APPROVED** [review]
Looks good, thanks for the PR! 👍

**Pull request merged**
