### PR TITLE
Isle of Armor Map Change

### PR DESCRIPTION
**Pull request by Qwertypop04**

### CODE REVIEW

**Review by Jaaslet — CHANGES_REQUESTED** [review]
Map looks good, and the SVG fits. Are the new sprites taken from the game, or do we need to add some credits?

**Comment by Jaaslet** [comment]
Ultima pointed out that the team rocket logo and the blimp base has been removed from the custom tile set

**Comment by Qwertypop04** [comment]
> Ultima pointed out that the team rocket logo and the blimp base has been removed from the custom tile set
Ah, whoops. I've fixed the tileset and the credits

**Review by Jaaslet — APPROVED** [review]
Looks good. Thanks for the PR

**Pull request merged**
