### PR TITLE
Copy base pokemon's level to evolved pokemon for real evolutions challenge mode

### PR DESCRIPTION
**Pull request by TheRealJoeFriel**
Quick fix for #3960, I saw that the exp for the pokemon was being carried over but the level was not. The level would be updated on subsequent gainExp calls since it would calculate the level from the level requirements and level type but until then it would remain at level 1.

### CODE REVIEW

**Comment by Jaaslet** [comment]
I don't think every evolution requires the same amount of exp to level up, as their baseform

**Comment by Razikd29** [comment]
Linked to #3960 ?

**Comment by Qwertypop04** [comment]
> I don't think every evolution requires the same amount of exp to level up, as their baseform

No, all Pokemon within an eventually family have the same experience group.

**Comment by PixLSteam** [comment]
Correct, that's what I read on Bulbapedia when I made the PR that copied the exp.

**Review by Jaaslet — APPROVED** [review]
Looks good. Thanks for the PR

**Pull request merged**
