### PR TITLE
Add hatchery filter to hide alternate forms

### PR DESCRIPTION
**Pull request by umbralOptimatum**
Adds a BreedingFilter to hide alternate forms in the hatchery, to help shiny hunt regional shiny achievements. Code copied and tweaked from the existing pokedex alternate filter, cursory test shows it behaves the same. Does not hide alternate forms native to other regions as those are part of the other regions' shiny completion.

Partially implements #4176.

### CODE REVIEW

**Comment by EatPant2nd** [comment]
But alternate forms work for those shiny regional achievements? The game only checks the integer part of the ID so alternate Bulbasaur (like Clone one) works for the shiny achievement.

**Comment by EatPant2nd** [comment]
I mean instead of just putting the alternates in a category after being done with that ID? I guess?

**Comment by RefRec97** [comment]
this filter exists in the pokedex and personally i think it would be a nice addition to the hatchery.

**Review by CypherX — APPROVED** [review]
The filter is in the pokedex so I think it's fine to also have in the hatchery. I made a very small styling tweak to reduce the empty space between it and the filters below.

Looks good 👍

**Pull request merged**
